/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage.gui.student;

import javax.swing.JOptionPane;
import mypackage.connector.LocalConnector;
import mypackage.repositories.interfaces.I_StudentRepository;
import mypackage.repositories.jdbc.StudentRepository;
import mypackage.utils.swing.Table;

import java.awt.event.KeyEvent;

/**
 *
 * @author andre
 */
public class JFrameVerStudent extends javax.swing.JFrame {

    private I_StudentRepository studentRepository = new StudentRepository(LocalConnector.getLocalConnection());

    /** Creates new form JFrameVerEmpleados */
    public JFrameVerStudent(boolean userRoot) {
        initComponents(userRoot);
        listarStudents();

    }

    public void listarStudents() {

        new Table().cargar(jTableListaStudents, studentRepository.getAll());
    }
    
    
    
   
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(boolean userRoot) {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jLabelTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListaStudents = new javax.swing.JTable();
        jButtonEliminar = new javax.swing.JButton();
        jButtonActualizar = new javax.swing.JButton();
        jLabelBusqueda = new javax.swing.JLabel();
        jTextFieldBusquedaStudents = new javax.swing.JTextField();
        jComboBoxBusquedaStudents = new javax.swing.JComboBox<>();
        jButtonRefrescarLista = new javax.swing.JButton();
        jButtonAnalytics = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitulo.setFont(new java.awt.Font("Arial Black", 1, 28)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("LISTA DE ESTUDIANTES");

        jTableListaStudents.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N
        jTableListaStudents.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTableListaStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableListaStudents.setToolTipText("");
        jScrollPane1.setViewportView(jTableListaStudents);

        jButtonEliminar.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jButtonEliminar.setText("ELIMINAR");
        jButtonEliminar.setVisible(userRoot);
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jButtonActualizar.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jButtonActualizar.setText("AGREGAR");
        jButtonActualizar.setVisible(userRoot);
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });

        jLabelBusqueda.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jLabelBusqueda.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBusqueda.setText("Buscar por :");

        jTextFieldBusquedaStudents.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTextFieldBusquedaStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBusquedaStudentsActionPerformed(evt);
            }
        });
        jTextFieldBusquedaStudents.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldBusquedaStudentsKeyReleased(evt);
            }
        });

        jComboBoxBusquedaStudents.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jComboBoxBusquedaStudents.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "ID", "NOMBRE", "APELLIDO", "EDAD", "GÉNERO", "FACULTAD", "CARRERA", "CORREO INSTITUCIONAL", "NÚMERO DE TELÉFONO", "SEMESTRE", "PROMEDIO", }));

        jButtonRefrescarLista.setBackground(new java.awt.Color(0, 34, 103));
        jButtonRefrescarLista.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonRefrescarLista.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRefrescarLista.setText("REFRESCAR LISTA");
        jButtonRefrescarLista.setVisible(userRoot);
        jButtonRefrescarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefrescarListaActionPerformed(evt);
            }
        });

        jButtonAnalytics.setBackground(new java.awt.Color(0, 34, 103));
        jButtonAnalytics.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonAnalytics.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAnalytics.setText("ANALYTICS");
        jButtonAnalytics.setVisible(false);//esto es para que no aparezca en la interfaz ya que no tine uso
        jButtonAnalytics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnalyticsActionPerformed(evt);
            }
        });

        jDesktopPane2.setLayer(jLabelTitulo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jButtonEliminar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jButtonActualizar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabelBusqueda, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jTextFieldBusquedaStudents, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jComboBoxBusquedaStudents, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jButtonRefrescarLista, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jButtonAnalytics, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelTitulo)
                        .addGap(347, 347, 347))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                        .addComponent(jLabelBusqueda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxBusquedaStudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jTextFieldBusquedaStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(282, 282, 282))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                        .addComponent(jButtonAnalytics, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(204, 204, 204)
                        .addComponent(jButtonActualizar)
                        .addGap(93, 93, 93)
                        .addComponent(jButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180)
                        .addComponent(jButtonRefrescarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBusqueda, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxBusquedaStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldBusquedaStudents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRefrescarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAnalytics, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13))))
        );

        jDesktopPane1.setLayer(jDesktopPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed

        int filaTablaStudent = jTableListaStudents.getSelectedRow();

        if (filaTablaStudent == -1) {

            JOptionPane.showMessageDialog(this, "SELECCIONE ALGUN ESTUDIANTE QUE DESEE ELIMINAR DE LA LISTA!");

            return;
        }

        String idStudent = (String) jTableListaStudents.getValueAt(filaTablaStudent, 0);



        if (JOptionPane.showConfirmDialog(this, "ESTA POR ELIMINAR EL ESTUDIANTE CON EL ID " + idStudent + "!!") != 0) {

            return;

        }

        studentRepository.remove(studentRepository.getById(idStudent));

        listarStudents();
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        new JFrameActualizarStudents().setVisible(true);
    }//GEN-LAST:event_jButtonActualizarActionPerformed

    private void jTextFieldBusquedaStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBusquedaEmpleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBusquedaEmpleadosActionPerformed

    private void jTextFieldBusquedaStudentsKeyReleased(KeyEvent evt) {//GEN-FIRST:event_jTextFieldBusquedaEmpleadosKeyReleased

        if (jComboBoxBusquedaStudents.getSelectedItem().equals("ID")) {

            new Table().cargar(jTableListaStudents, studentRepository.getLikeId(jTextFieldBusquedaStudents.getText()));

        } else if (jComboBoxBusquedaStudents.getSelectedItem().equals("NOMBRE")) {

            new Table().cargar(jTableListaStudents, studentRepository.getLikeNombre(jTextFieldBusquedaStudents.getText()));

        } else if (jComboBoxBusquedaStudents.getSelectedItem().equals("APELLIDO")) {

            new Table().cargar(jTableListaStudents, studentRepository.getLikeApellido(jTextFieldBusquedaStudents.getText()));

        } else if (jComboBoxBusquedaStudents.getSelectedItem().equals("EDAD")) {

            new Table().cargar(jTableListaStudents, studentRepository.getLikeEdad(jTextFieldBusquedaStudents.getText()));

        } else if (jComboBoxBusquedaStudents.getSelectedItem().equals("GÉNERO")) {

            new Table().cargar(jTableListaStudents, studentRepository.getLikeGenero(jTextFieldBusquedaStudents.getText()));

        } else if (jComboBoxBusquedaStudents.getSelectedItem().equals("FACULTAD")) {

            new Table().cargar(jTableListaStudents, studentRepository.getLikeFacultad(jTextFieldBusquedaStudents.getText()));

        } else if (jComboBoxBusquedaStudents.getSelectedItem().equals("CARRERA")) {

            new Table().cargar(jTableListaStudents, studentRepository.getLikecarrera(jTextFieldBusquedaStudents.getText()));

        } else if (jComboBoxBusquedaStudents.getSelectedItem().equals("CORREO INSTITUCIONAL")) {

            new Table().cargar(jTableListaStudents, studentRepository.getLikeCorreoInstituconal(jTextFieldBusquedaStudents.getText()));

        } else if (jComboBoxBusquedaStudents.getSelectedItem().equals("NÚMERO DE TELÉFONO")) {

            new Table().cargar(jTableListaStudents, studentRepository.getLikeNumeroTelefono(jTextFieldBusquedaStudents.getText()));

        } else if (jComboBoxBusquedaStudents.getSelectedItem().equals("SEMESTRE")) {

            new Table().cargar(jTableListaStudents, studentRepository.getLikeSemestre(jTextFieldBusquedaStudents.getText()));

        } else if (jComboBoxBusquedaStudents.getSelectedItem().equals("PROMEDIO")) {

            new Table().cargar(jTableListaStudents, studentRepository.getLikePromedio(jTextFieldBusquedaStudents.getText()));

        }

    }//GEN-LAST:event_jTextFieldBusquedaEmpleadosKeyReleased

    private void jButtonRefrescarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefrescarListaActionPerformed

        new Table().cargar(jTableListaStudents, studentRepository.getAll());
    }//GEN-LAST:event_jButtonRefrescarListaActionPerformed

    private void jButtonAnalyticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnalyticsActionPerformed
  //     new JFrameAnalytics().setVisible(true);


    }//GEN-LAST:event_jButtonAnalyticsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[],boolean userRoot) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameVerStudent.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameVerStudent.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameVerStudent.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameVerStudent.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameVerStudent(userRoot).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonAnalytics;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonRefrescarLista;
    private javax.swing.JComboBox<String> jComboBoxBusquedaStudents;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabelBusqueda;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListaStudents;
    private javax.swing.JTextField jTextFieldBusquedaStudents;
    // End of variables declaration//GEN-END:variables
}
