/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage.gui.student;


import mypackage.entities.Student;
import mypackage.repositories.jdbc.StudentRepository;
import mypackage.connector.LocalConnector;
import javax.swing.JOptionPane;


/**
 *
 * @author andre
 */
public class JFrameActualizarStudents extends javax.swing.JFrame {//refactor class name from Employee to Student

    /** Creates new form JFrameActualizarEmpleados */
    public JFrameActualizarStudents() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
/*NotaPersonal: los jTextFile(son caja de textos||TextBox) no es necesario modificarlos más que sus nombres
               los jLabel(son etiquetas||labels)estas si se deben mificar su contenido y nombre
 */
        jDesktopPane1 = new javax.swing.JDesktopPane();                 //listo
        jLabelTitulo = new javax.swing.JLabel();                        //modificado
        jLabelNombre = new javax.swing.JLabel();                        //modificado
        jTextFieldNombre = new javax.swing.JTextField();                //listo
        jLabelApellido = new javax.swing.JLabel();                      //Listo
        jTextFieldApellido = new javax.swing.JTextField();              //listo
        jLabelEdad = new javax.swing.JLabel();                          //listo
        jTextFieldEdad = new javax.swing.JTextField();                  //listo
        jLabelGenero = new javax.swing.JLabel();                        //listo
        jTextFieldGenero = new javax.swing.JTextField();                //listo
        jTextFieldPromeido = new javax.swing.JTextField();              //listo
        jLabelCorreoInstitucional2 = new javax.swing.JLabel();          //listo
        jTextFieldFacultad = new javax.swing.JTextField();              //listo
        jLabelFacultad = new javax.swing.JLabel();                      //listo
        jLabelMatricula = new javax.swing.JLabel();
        jLabelPromedio = new javax.swing.JLabel();
        jTextFieldMatricula = new javax.swing.JTextField();
        jLabelCorreoInstitucional1 = new javax.swing.JLabel();
        jLabelNumero2 = new javax.swing.JLabel();
        jTextFieldCorreoInstitucional = new javax.swing.JTextField();
        jLabelNumero3 = new javax.swing.JLabel();
        jTextFieldNumeroTelefono = new javax.swing.JTextField();
        jLabelCarrera = new javax.swing.JLabel();
        jLabelSemestre = new javax.swing.JLabel();
        jTextFieldCarrera = new javax.swing.JTextField();
        jTextFieldSemestre = new javax.swing.JTextField();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonActualizar = new javax.swing.JButton();
        jButtonVerStudents = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitulo.setFont(new java.awt.Font("Arial", 1, 32)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("ACTUALIZACIÓN DE ESTUDIANTES");
        jDesktopPane1.add(jLabelTitulo);
        jLabelTitulo.setBounds(40, 20, 610, 42);

        jLabelNombre.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setText("Nombre:");
        jDesktopPane1.add(jLabelNombre);
        jLabelNombre.setBounds(170, 80, 98, 28);

        jTextFieldNombre.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldNombre);
        jTextFieldNombre.setBounds(260, 80, 191, 34);

        jLabelApellido.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelApellido.setForeground(new java.awt.Color(255, 255, 255));
        jLabelApellido.setText("Apellido:");
        jDesktopPane1.add(jLabelApellido);
        jLabelApellido.setBounds(170, 120, 104, 28);

        jTextFieldApellido.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldApellido);
        jTextFieldApellido.setBounds(260, 120, 191, 34);

        jLabelEdad.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelEdad.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEdad.setText("Edad:");
        jDesktopPane1.add(jLabelEdad);
        jLabelEdad.setBounds(200, 160, 55, 24);

        jTextFieldEdad.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldEdad);
        jTextFieldEdad.setBounds(260, 160, 191, 34);

        jLabelGenero.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelGenero.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGenero.setText("Genero:");
        jDesktopPane1.add(jLabelGenero);
        jLabelGenero.setBounds(180, 200, 77, 24);

        jTextFieldGenero.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldGenero);
        jTextFieldGenero.setBounds(260, 200, 191, 34);

        jTextFieldPromeido.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldPromeido);
        jTextFieldPromeido.setBounds(260, 600, 191, 34);


        jLabelCorreoInstitucional2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelCorreoInstitucional2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCorreoInstitucional2.setText("istitucional:");
        jDesktopPane1.add(jLabelCorreoInstitucional2);
        jLabelCorreoInstitucional2.setBounds(140, 370, 120, 40);

        jTextFieldFacultad.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldFacultad);
        jTextFieldFacultad.setBounds(260, 250, 191, 30);

        jLabelFacultad.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelFacultad.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFacultad.setText("Facultad:");
        jDesktopPane1.add(jLabelFacultad);
        jLabelFacultad.setBounds(160, 250, 120, 30);///Referencia de modificación y+=20 width+=40

        jLabelMatricula.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelMatricula.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMatricula.setText("Matricula:");
        jDesktopPane1.add(jLabelMatricula);
        jLabelMatricula.setBounds(140, 310, 110, 30);

        jLabelPromedio.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelPromedio.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPromedio.setText("Promedio:");
        jDesktopPane1.add(jLabelPromedio);
        jLabelPromedio.setBounds(160, 590, 120, 40);

        jTextFieldMatricula.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldMatricula);
        jTextFieldMatricula.setBounds(260, 310, 191, 34);

        jLabelCorreoInstitucional1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelCorreoInstitucional1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCorreoInstitucional1.setText("Correo");
        jDesktopPane1.add(jLabelCorreoInstitucional1);
        jLabelCorreoInstitucional1.setBounds(170, 350, 70, 40);

        jLabelNumero2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelNumero2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumero2.setText("de telefono:");
        jDesktopPane1.add(jLabelNumero2);
        jLabelNumero2.setBounds(140, 430, 130, 40);

        jTextFieldCorreoInstitucional.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldCorreoInstitucional);
        jTextFieldCorreoInstitucional.setBounds(260, 370, 191, 34);

        jLabelNumero3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelNumero3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumero3.setText("Numero ");
        jDesktopPane1.add(jLabelNumero3);
        jLabelNumero3.setBounds(160, 410, 110, 40);


        jTextFieldNumeroTelefono.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldNumeroTelefono);
        jTextFieldNumeroTelefono.setBounds(260, 430, 191, 34);

        jLabelCarrera.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelCarrera.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCarrera.setText("Carrera:");
        jDesktopPane1.add(jLabelCarrera);
        jLabelCarrera.setBounds(170, 490, 90, 40);

        jLabelSemestre.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelSemestre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSemestre.setText("Semestre:");
        jDesktopPane1.add(jLabelSemestre);
        jLabelSemestre.setBounds(160, 550, 120, 40);

        jTextFieldCarrera.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldCarrera);
        jTextFieldCarrera.setBounds(260, 490, 191, 34);


        jTextFieldSemestre.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldSemestre);
        jTextFieldSemestre.setBounds(260, 550, 191, 34);

        jButtonLimpiar.setBackground(new java.awt.Color(0, 32, 108));
        jButtonLimpiar.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButtonLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLimpiar.setText("Limpiar ");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButtonLimpiar);
        jButtonLimpiar.setBounds(160, 680, 142, 50);

        jButtonActualizar.setBackground(new java.awt.Color(0, 32, 108));
        jButtonActualizar.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButtonActualizar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonActualizar.setText("Actualizar");
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButtonActualizar);
        jButtonActualizar.setBounds(340, 680, 140, 50);

        jButtonVerStudents.setBackground(new java.awt.Color(1, 26, 86));
        jButtonVerStudents.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButtonVerStudents.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVerStudents.setText("Ver Estudiantes");
        jButtonVerStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregar1ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButtonVerStudents);
        jButtonVerStudents.setBounds(240, 760, 180, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed

        jTextFieldNombre.setText("");
        jTextFieldApellido.setText("");
        jTextFieldSemestre.setText("");
        jTextFieldCorreoInstitucional.setText("");
        jTextFieldEdad.setText("");
        jTextFieldCarrera.setText("");
        jTextFieldGenero.setText("");
        jTextFieldMatricula.setText("");
        jTextFieldNumeroTelefono.setText("");
        jTextFieldPromeido.setText("");
        jTextFieldFacultad.setText("");
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        // TODO add your handling code here:
        try {
            StudentRepository repo = new StudentRepository(LocalConnector.getLocalConnection());

            String id =jTextFieldMatricula.getText().trim();
            String nombre = jTextFieldNombre.getText().trim();
            String apellido = jTextFieldApellido.getText().trim();
            int edad = Integer.parseInt(jTextFieldEdad.getText().trim());
            String genero = jTextFieldGenero.getText().trim();
            String facultad = jTextFieldFacultad.getText().trim();
            String correo = jTextFieldCorreoInstitucional.getText().trim();
            String cel = jTextFieldNumeroTelefono.getText().trim();
            String carrera = jTextFieldCarrera.getText().trim();
            int semestre = Integer.parseInt(jTextFieldSemestre.getText().trim());
            int promedio = Integer.parseInt(jTextFieldPromeido.getText().trim());

            if(!id.matches("^\\d{8}$")){
                JOptionPane.showMessageDialog(this, "INGRESE UNA MATRÍCULA VÁLIDA DE 8 DÍGITOS.");
                return;
            }
            /// intentar validar el correo con la matrícula
            if (!correo.matches("^[\\w\\.-]+@[\\w\\.-]+\\.[a-zA-Z]{2,6}$")) {
                JOptionPane.showMessageDialog(this, "INGRESE UN CORREO INSTITUCIONAL VÁLIDO (aMatrícula@alumnos.uady.mx)");
                return;
            }
            if (!cel.matches("^\\d{10}$")) {
                JOptionPane.showMessageDialog(this, "INGRESE UN NÚMERO TELEFÓNICO VÁLIDO DE 10 DÍGITOS.");
                return;
            }
            try {
                if (semestre<1||semestre>14){JOptionPane.showMessageDialog(this,"EL SEMESTRE DEBE ESTAR ENTRE 1 Y 14");return;}
            }catch (NumberFormatException exception){JOptionPane.showMessageDialog(this,"NÚMERO DE SEMESTRE NO VÁLIDO");return;}
            try {
                if(edad<17||edad>100){JOptionPane.showMessageDialog(this,"LA EDAD DEBE ESTAR ENTRE 17 Y 100");return;}
            }catch (NumberFormatException exception){JOptionPane.showMessageDialog(this,"NÚMERO DE EDAD NO VÁLIDA");return;}
            try {
                if(promedio<0||promedio>100){JOptionPane.showMessageDialog(this,"EL PROMEDIO DEBE ESTAR ENTRE 0 Y 100");return;}
            }catch (NumberFormatException exception){JOptionPane.showMessageDialog(this,"FORMATO DE PROMEDIO NO VÁLIDO");return;}



            Student student = new Student(id,nombre,apellido,edad,genero,facultad,carrera,correo,cel,semestre,promedio);

            repo.save(student);
            JOptionPane.showMessageDialog(this, "Estudiante actualizado con éxito");

        }catch (Exception e){
            JOptionPane.showMessageDialog(this, "Error al actualizar: " + e.getMessage());
            e.printStackTrace();
        }


    }//GEN-LAST:event_jButtonActualizarActionPerformed

    private void jButtonAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregar1ActionPerformed
        // TODO add your handling code here:
        new JFrameVerStudent(true).setVisible(true);
    }//GEN-LAST:event_jButtonAgregar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameActualizarStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameActualizarStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameActualizarStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameActualizarStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameActualizarStudents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonVerStudents;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabelApellido;                                 //Listo
    private javax.swing.JLabel jLabelSemestre;                                //listo
    private javax.swing.JLabel jLabelCorreoInstitucional2;                    //listo
    private javax.swing.JLabel jLabelCorreoInstitucional1;                    //listo
    private javax.swing.JLabel jLabelEdad;                                    //listo
    private javax.swing.JLabel jLabelCarrera;                                 //listo
    private javax.swing.JLabel jLabelGenero;                                  //listo
    private javax.swing.JLabel jLabelNombre;                                  //Modificado
    private javax.swing.JLabel jLabelMatricula;                             //listo
    private javax.swing.JLabel jLabelNumero2;                               //listo
    private javax.swing.JLabel jLabelNumero3;                               //listo
    private javax.swing.JLabel jLabelPromedio;                              //listo
    private javax.swing.JLabel jLabelFacultad;                             //listo
    private javax.swing.JLabel jLabelTitulo;                               //modificado
    private javax.swing.JTextField jTextFieldApellido;                     //Listo
    private javax.swing.JTextField jTextFieldSemestre;                      //listo
    private javax.swing.JTextField jTextFieldCorreoInstitucional;           //listo
    private javax.swing.JTextField jTextFieldEdad;                          //listo
    private javax.swing.JTextField jTextFieldCarrera;                       //listo
    private javax.swing.JTextField jTextFieldGenero;                        //listo
    private javax.swing.JTextField jTextFieldNombre;                        //mantener
    private javax.swing.JTextField jTextFieldMatricula;                     //listo
    private javax.swing.JTextField jTextFieldNumeroTelefono;                //listo
    private javax.swing.JTextField jTextFieldPromeido;                      //listo
    private javax.swing.JTextField jTextFieldFacultad;                      //listo
    // End of variables declaration//GEN-END:variables
}
