/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


package mypackage.gui.estudiante;

/**
 *
 * @author andre
 */
public class JFrameIngresoEstudiante extends javax.swing.JFrame {

    /** Creates new form JFrameestudiantes */
    public JFrameIngresoEstudiante() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelApellido = new javax.swing.JLabel();
        jTextFieldApellido = new javax.swing.JTextField();
        jLabelEdad = new javax.swing.JLabel();
        jTextFieldEdad = new javax.swing.JTextField();
        jLabelGenero = new javax.swing.JLabel();
        jTextFieldGenero = new javax.swing.JTextField();
        jLabelcalificacion = new javax.swing.JLabel();
        jLabelCorreo1 = new javax.swing.JLabel();
        jTextFieldmatricula = new javax.swing.JTextField();
        jLabelmatricula = new javax.swing.JLabel();
        jTextFieldcalificacion = new javax.swing.JTextField();
        jLabelCorreo3 = new javax.swing.JLabel();
        jLabelNumero2 = new javax.swing.JLabel();
        jTextFieldCorreoElectronico = new javax.swing.JTextField();
        jLabelNumero3 = new javax.swing.JLabel();
        jLabelFecha2 = new javax.swing.JLabel();
        jTextFieldNumeroTelefono = new javax.swing.JTextField();
        jLabelFecha3 = new javax.swing.JLabel();
        jTextFieldFechaDeInicio = new javax.swing.JTextField();
        jLabelsemestre = new javax.swing.JLabel();
        jTextFieldsemestre = new javax.swing.JTextField();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonAgregar = new javax.swing.JButton();
        jButtonAgregar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("INGRESAR ESTUDIANTE");
        jDesktopPane1.add(jLabelTitulo);
        jLabelTitulo.setBounds(120, 20, 430, 42);

        jLabelNombre.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setText("Nombre:");
        jDesktopPane1.add(jLabelNombre);
        jLabelNombre.setBounds(20, 70, 98, 28);

        jTextFieldNombre.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldNombre);
        jTextFieldNombre.setBounds(110, 70, 191, 28);

        jLabelApellido.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelApellido.setForeground(new java.awt.Color(255, 255, 255));
        jLabelApellido.setText("Apellido:");
        jDesktopPane1.add(jLabelApellido);
        jLabelApellido.setBounds(330, 70, 104, 28);

        jTextFieldApellido.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldApellido);
        jTextFieldApellido.setBounds(420, 70, 191, 28);

        jLabelEdad.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelEdad.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEdad.setText("Edad:");
        jDesktopPane1.add(jLabelEdad);
        jLabelEdad.setBounds(30, 110, 55, 24);

        jTextFieldEdad.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldEdad);
        jTextFieldEdad.setBounds(110, 110, 70, 28);

        jLabelGenero.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelGenero.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGenero.setText("Genero:");
        jDesktopPane1.add(jLabelGenero);
        jLabelGenero.setBounds(200, 110, 77, 24);

        jTextFieldGenero.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldGenero);
        jTextFieldGenero.setBounds(290, 110, 150, 28);

        jLabelcalificacion.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelcalificacion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelcalificacion.setText("Calificacion:");
        jDesktopPane1.add(jLabelcalificacion);
        jLabelcalificacion.setBounds(440, 100, 120, 40);

        jLabelCorreo1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelCorreo1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCorreo1.setText("electrónico:");
        jDesktopPane1.add(jLabelCorreo1);
        jLabelCorreo1.setBounds(330, 160, 120, 40);

        jTextFieldmatricula.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldmatricula);
        jTextFieldmatricula.setBounds(120, 150, 191, 30);

        jLabelmatricula.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelmatricula.setForeground(new java.awt.Color(255, 255, 255));
        jLabelmatricula.setText("Matricula:");
        jDesktopPane1.add(jLabelmatricula);
        jLabelmatricula.setBounds(20, 150, 120, 40);

        jTextFieldcalificacion.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldcalificacion);
        jTextFieldcalificacion.setBounds(560, 110, 70, 28);

        jLabelCorreo3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelCorreo3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCorreo3.setText("Correo");
        jDesktopPane1.add(jLabelCorreo3);
        jLabelCorreo3.setBounds(350, 140, 70, 40);

        jLabelNumero2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelNumero2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumero2.setText("de telefono:");
        jDesktopPane1.add(jLabelNumero2);
        jLabelNumero2.setBounds(20, 200, 130, 40);

        jTextFieldCorreoElectronico.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldCorreoElectronico);
        jTextFieldCorreoElectronico.setBounds(450, 150, 191, 28);

        jLabelNumero3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelNumero3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumero3.setText("Numero ");
        jDesktopPane1.add(jLabelNumero3);
        jLabelNumero3.setBounds(40, 180, 110, 40);

        jLabelFecha2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelFecha2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFecha2.setText("de inicio:");
        jDesktopPane1.add(jLabelFecha2);
        jLabelFecha2.setBounds(340, 210, 100, 40);

        jTextFieldNumeroTelefono.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldNumeroTelefono);
        jTextFieldNumeroTelefono.setBounds(140, 200, 191, 28);

        jLabelFecha3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelFecha3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFecha3.setText("Fecha ");
        jDesktopPane1.add(jLabelFecha3);
        jLabelFecha3.setBounds(350, 190, 90, 40);

        jTextFieldFechaDeInicio.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldFechaDeInicio);
        jTextFieldFechaDeInicio.setBounds(440, 200, 191, 28);

        jLabelsemestre.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelsemestre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelsemestre.setText("Semestre");
        jDesktopPane1.add(jLabelsemestre);
        jLabelsemestre.setBounds(20, 250, 110, 40);

        jTextFieldsemestre.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldsemestre);
        jTextFieldsemestre.setBounds(120, 250, 191, 28);

        jButtonLimpiar.setBackground(new java.awt.Color(0, 32, 108));
        jButtonLimpiar.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButtonLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLimpiar.setText("Limpiar ");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButtonLimpiar);
        jButtonLimpiar.setBounds(20, 310, 142, 50);

        jButtonAgregar.setBackground(new java.awt.Color(0, 32, 108));
        jButtonAgregar.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButtonAgregar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButtonAgregar);
        jButtonAgregar.setBounds(480, 300, 140, 50);

        jButtonAgregar1.setBackground(new java.awt.Color(1, 26, 86));
        jButtonAgregar1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButtonAgregar1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAgregar1.setText("LISTA DE ESTUDIANTES");
        jButtonAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregar1ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButtonAgregar1);
        jButtonAgregar1.setBounds(190, 300, 270, 60);

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 670, 870));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed

        jTextFieldNombre.setText("");
        jTextFieldApellido.setText("");
       // jTextFieldCantidadHsSemanales.setText("");
        jTextFieldCorreoElectronico.setText("");
        jTextFieldEdad.setText("");
        jTextFieldFechaDeInicio.setText("");
        jTextFieldGenero.setText("");
        jTextFieldcalificacion.setText("");
        jTextFieldNumeroTelefono.setText("");
        jTextFieldmatricula.setText("");
        jTextFieldcalificacion.setText("");
        jTextFieldsemestre.setText("");
        jTextFieldmatricula.setText("");

    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregar1ActionPerformed
       new JFrameVerEstudiante().setVisible(true);
    }//GEN-LAST:event_jButtonAgregar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameIngresoEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameIngresoEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameIngresoEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameIngresoEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameIngresoEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonAgregar1;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelCorreo1;
    private javax.swing.JLabel jLabelCorreo3;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JLabel jLabelFecha2;
    private javax.swing.JLabel jLabelFecha3;
    private javax.swing.JLabel jLabelGenero;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNumero2;
    private javax.swing.JLabel jLabelNumero3;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelcalificacion;
    private javax.swing.JLabel jLabelmatricula;
    private javax.swing.JLabel jLabelsemestre;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldCorreoElectronico;
    private javax.swing.JTextField jTextFieldEdad;
    private javax.swing.JTextField jTextFieldFechaDeInicio;
    private javax.swing.JTextField jTextFieldGenero;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNumeroTelefono;
    private javax.swing.JTextField jTextFieldcalificacion;
    private javax.swing.JTextField jTextFieldmatricula;
    private javax.swing.JTextField jTextFieldsemestre;
    // End of variables declaration//GEN-END:variables
}
