/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage.gui.estudiante;

import javax.swing.*;

/**
 *
 * @author andre
 */
public class JFrameActualizarEstudiante extends javax.swing.JFrame {

    /** Creates new form JFrameActualizarestudiantes */
    public JFrameActualizarEstudiante() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPanerosadito = new javax.swing.JDesktopPane();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelApellido = new javax.swing.JLabel();
        jTextFieldApellido = new javax.swing.JTextField();
        jLabelEdad = new javax.swing.JLabel();
        jTextFieldEdad = new javax.swing.JTextField();
        jLabelGenero = new javax.swing.JLabel();
        jTextFieldGenero = new javax.swing.JTextField();
        jTextFieldmatricula = new javax.swing.JTextField();
        jLabelNumDoc2 = new javax.swing.JLabel();
        jLabelCorreo1 = new javax.swing.JLabel();
        jTextFieldTipoDoc = new javax.swing.JTextField();
        jLabelTipoDoc3 = new javax.swing.JLabel();
        jLabelTipoDoc4 = new javax.swing.JLabel();
        jLabelNumDoc3 = new javax.swing.JLabel();
        jLabelmatricula = new javax.swing.JLabel();
        jTextFieldNumDoc = new javax.swing.JTextField();
        jLabelCorreo3 = new javax.swing.JLabel();
        jLabelNumero2 = new javax.swing.JLabel();
        jTextFieldCorreoElectronico = new javax.swing.JTextField();
        jLabelNumero3 = new javax.swing.JLabel();
        jLabelFecha2 = new javax.swing.JLabel();
        jTextFieldNumeroTelefono = new javax.swing.JTextField();
        jLabelFecha3 = new javax.swing.JLabel();
        jLabelCantidadHs1 = new javax.swing.JLabel();
        jTextFieldFechaDeInicio = new javax.swing.JTextField();
        jLabelCantidadHs3 = new javax.swing.JLabel();
        jTextFieldCantidadHsSemanales = new javax.swing.JTextField();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonActualizar = new javax.swing.JButton();
        jButtonAgregar1 = new javax.swing.JButton();
        jLabelcalificacion = new javax.swing.JLabel();
        jTextFieldcalificacion = new javax.swing.JTextField();
        jLabelsemestre = new javax.swing.JLabel();
        jTextFieldsemestre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPanerosadito.setBackground(new java.awt.Color(255, 204, 255));
        jDesktopPanerosadito.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelTitulo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Actualización de estudiantes");
        jDesktopPanerosadito.add(jLabelTitulo);
        jLabelTitulo.setBounds(80, 20, 490, 42);

        jLabelNombre.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setText("Nombre:");
        jDesktopPanerosadito.add(jLabelNombre);
        jLabelNombre.setBounds(20, 80, 98, 28);

        jTextFieldNombre.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPanerosadito.add(jTextFieldNombre);
        jTextFieldNombre.setBounds(120, 80, 140, 28);

        jLabelApellido.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelApellido.setForeground(new java.awt.Color(255, 255, 255));
        jLabelApellido.setText("Apellido:");
        jDesktopPanerosadito.add(jLabelApellido);
        jLabelApellido.setBounds(10, 120, 104, 28);

        jTextFieldApellido.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPanerosadito.add(jTextFieldApellido);
        jTextFieldApellido.setBounds(120, 120, 150, 28);

        jLabelEdad.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelEdad.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEdad.setText("Edad:");
        jDesktopPanerosadito.add(jLabelEdad);
        jLabelEdad.setBounds(360, 80, 55, 24);

        jTextFieldEdad.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPanerosadito.add(jTextFieldEdad);
        jTextFieldEdad.setBounds(450, 80, 80, 28);

        jLabelGenero.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelGenero.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGenero.setText("Genero:");
        jDesktopPanerosadito.add(jLabelGenero);
        jLabelGenero.setBounds(350, 120, 77, 24);

        jTextFieldGenero.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPanerosadito.add(jTextFieldGenero);
        jTextFieldGenero.setBounds(450, 120, 191, 28);

        jTextFieldmatricula.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPanerosadito.add(jTextFieldmatricula);
        jTextFieldmatricula.setBounds(330, 370, 191, 28);

        jLabelNumDoc2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelNumDoc2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumDoc2.setText("documento:");
        jDesktopPanerosadito.add(jLabelNumDoc2);
        jLabelNumDoc2.setBounds(0, 240, 120, 40);

        jLabelCorreo1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelCorreo1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCorreo1.setText("electrónico:");
        jDesktopPanerosadito.add(jLabelCorreo1);
        jLabelCorreo1.setBounds(330, 170, 120, 40);

        jTextFieldTipoDoc.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPanerosadito.add(jTextFieldTipoDoc);
        jTextFieldTipoDoc.setBounds(120, 180, 191, 30);

        jLabelTipoDoc3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelTipoDoc3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTipoDoc3.setText("Tipo de");
        jDesktopPanerosadito.add(jLabelTipoDoc3);
        jLabelTipoDoc3.setBounds(20, 160, 80, 30);

        jLabelTipoDoc4.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelTipoDoc4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTipoDoc4.setText("documento:");
        jDesktopPanerosadito.add(jLabelTipoDoc4);
        jLabelTipoDoc4.setBounds(0, 180, 120, 40);

        jLabelNumDoc3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelNumDoc3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumDoc3.setText("Numero de");
        jDesktopPanerosadito.add(jLabelNumDoc3);
        jLabelNumDoc3.setBounds(10, 220, 110, 30);

        jLabelmatricula.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelmatricula.setForeground(new java.awt.Color(255, 255, 255));
        jLabelmatricula.setText("matricula:");
        jDesktopPanerosadito.add(jLabelmatricula);
        jLabelmatricula.setBounds(210, 360, 130, 40);

        jTextFieldNumDoc.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPanerosadito.add(jTextFieldNumDoc);
        jTextFieldNumDoc.setBounds(120, 240, 70, 28);

        jLabelCorreo3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelCorreo3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCorreo3.setText("Correo");
        jDesktopPanerosadito.add(jLabelCorreo3);
        jLabelCorreo3.setBounds(360, 150, 70, 40);

        jLabelNumero2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelNumero2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumero2.setText("de telefono:");
        jDesktopPanerosadito.add(jLabelNumero2);
        jLabelNumero2.setBounds(210, 240, 120, 40);

        jTextFieldCorreoElectronico.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPanerosadito.add(jTextFieldCorreoElectronico);
        jTextFieldCorreoElectronico.setBounds(450, 170, 191, 28);

        jLabelNumero3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelNumero3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumero3.setText("Numero ");
        jDesktopPanerosadito.add(jLabelNumero3);
        jLabelNumero3.setBounds(230, 210, 110, 40);

        jLabelFecha2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelFecha2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFecha2.setText("inicio:");
        jDesktopPanerosadito.add(jLabelFecha2);
        jLabelFecha2.setBounds(30, 300, 60, 40);

        jTextFieldNumeroTelefono.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPanerosadito.add(jTextFieldNumeroTelefono);
        jTextFieldNumeroTelefono.setBounds(330, 230, 191, 28);

        jLabelFecha3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelFecha3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFecha3.setText("Fecha de");
        jDesktopPanerosadito.add(jLabelFecha3);
        jLabelFecha3.setBounds(10, 270, 90, 40);

        jLabelCantidadHs1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelCantidadHs1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCantidadHs1.setText("Cantidad hs");
        jDesktopPanerosadito.add(jLabelCantidadHs1);
        jLabelCantidadHs1.setBounds(10, 340, 120, 40);

        jTextFieldFechaDeInicio.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPanerosadito.add(jTextFieldFechaDeInicio);
        jTextFieldFechaDeInicio.setBounds(110, 300, 140, 28);

        jLabelCantidadHs3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelCantidadHs3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCantidadHs3.setText("semanales:");
        jDesktopPanerosadito.add(jLabelCantidadHs3);
        jLabelCantidadHs3.setBounds(10, 370, 110, 40);

        jTextFieldCantidadHsSemanales.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPanerosadito.add(jTextFieldCantidadHsSemanales);
        jTextFieldCantidadHsSemanales.setBounds(120, 370, 80, 28);

        jButtonLimpiar.setBackground(new java.awt.Color(0, 32, 108));
        jButtonLimpiar.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButtonLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLimpiar.setText("Limpiar ");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });
        jDesktopPanerosadito.add(jButtonLimpiar);
        jButtonLimpiar.setBounds(580, 350, 142, 50);

        jButtonActualizar.setBackground(new java.awt.Color(0, 32, 108));
        jButtonActualizar.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButtonActualizar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonActualizar.setText("Actualizar");
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });
        jDesktopPanerosadito.add(jButtonActualizar);
        jButtonActualizar.setBounds(580, 220, 140, 50);

        jButtonAgregar1.setBackground(new java.awt.Color(1, 26, 86));
        jButtonAgregar1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButtonAgregar1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAgregar1.setText("Ver estudiantes");
        jButtonAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregar1ActionPerformed(evt);
            }
        });
        jDesktopPanerosadito.add(jButtonAgregar1);
        jButtonAgregar1.setBounds(560, 280, 180, 50);

        jLabelcalificacion.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelcalificacion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelcalificacion.setText("calificación:");
        jDesktopPanerosadito.add(jLabelcalificacion);
        jLabelcalificacion.setBounds(260, 300, 140, 20);

        jTextFieldcalificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldcalificacionActionPerformed(evt);
            }
        });
        jDesktopPanerosadito.add(jTextFieldcalificacion);
        jTextFieldcalificacion.setBounds(400, 290, 80, 40);

        jLabelsemestre.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelsemestre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelsemestre.setText("semestre:");
        jDesktopPanerosadito.add(jLabelsemestre);
        jLabelsemestre.setBounds(10, 430, 120, 20);

        jTextFieldsemestre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldsemestreActionPerformed(evt);
            }
        });
        jDesktopPanerosadito.add(jTextFieldsemestre);
        jTextFieldsemestre.setBounds(130, 420, 190, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addComponent(jDesktopPanerosadito, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPanerosadito, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 303, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed

        jTextFieldNombre.setText("");
        jTextFieldApellido.setText("");
        jTextFieldCantidadHsSemanales.setText("");
        jTextFieldCorreoElectronico.setText("");
        jTextFieldEdad.setText("");
        jTextFieldFechaDeInicio.setText("");
        jTextFieldGenero.setText("");
        jTextFieldNumDoc.setText("");
        jTextFieldNumeroTelefono.setText("");
        jTextFieldmatricula.setText("");
        jTextFieldTipoDoc.setText("");
        jTextFieldcalificacion.setText("");
        jTextFieldsemestre.setText("");
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonActualizarActionPerformed

    private void jButtonAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAgregar1ActionPerformed

    private void jTextFieldcalificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldcalificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldcalificacionActionPerformed

    private void jTextFieldsemestreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldsemestreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldsemestreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameActualizarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameActualizarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameActualizarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameActualizarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameActualizarEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonAgregar1;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JDesktopPane jDesktopPanerosadito;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelCantidadHs1;
    private javax.swing.JLabel jLabelCantidadHs3;
    private javax.swing.JLabel jLabelCorreo1;
    private javax.swing.JLabel jLabelCorreo3;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JLabel jLabelFecha2;
    private javax.swing.JLabel jLabelFecha3;
    private javax.swing.JLabel jLabelGenero;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNumDoc2;
    private javax.swing.JLabel jLabelNumDoc3;
    private javax.swing.JLabel jLabelNumero2;
    private javax.swing.JLabel jLabelNumero3;
    private javax.swing.JLabel jLabelTipoDoc3;
    private javax.swing.JLabel jLabelTipoDoc4;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelcalificacion;
    private javax.swing.JLabel jLabelmatricula;
    private javax.swing.JLabel jLabelsemestre;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldCantidadHsSemanales;
    private javax.swing.JTextField jTextFieldCorreoElectronico;
    private javax.swing.JTextField jTextFieldEdad;
    private javax.swing.JTextField jTextFieldFechaDeInicio;
    private javax.swing.JTextField jTextFieldGenero;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNumDoc;
    private javax.swing.JTextField jTextFieldNumeroTelefono;
    private javax.swing.JTextField jTextFieldTipoDoc;
    private javax.swing.JTextField jTextFieldcalificacion;
    private javax.swing.JTextField jTextFieldmatricula;
    private javax.swing.JTextField jTextFieldsemestre;
    // End of variables declaration//GEN-END:variables
}
