/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage.gui.menuInicial;

import mypackage.connector.LocalConnector;
import mypackage.gui.utils.JFrameValidacionIngreso;
import mypackage.gui.otros.JFrameAcercaDe;
import mypackage.gui.otros.JFrameAyuda;
import mypackage.repositories.interfaces.I_EstudianteRepository;
import mypackage.repositories.jdbc.EstudianteRepository;

/**
 *
 * @author andre
 */
public class JFrameGestorEstudiantes_app extends javax.swing.JFrame {
    
    
      I_EstudianteRepository EstudianteRepository = new EstudianteRepository(LocalConnector.getLocalConnection());


    /** Creates new form JFrameGestorEstudiantes_app */
    public JFrameGestorEstudiantes_app() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneFondo = new javax.swing.JDesktopPane();
        jButtonEstudiantes = new javax.swing.JButton();
        jButtonactuarios = new javax.swing.JButton();
        jButtonLicCienciasComputacion = new javax.swing.JButton();
        jButtonlicIngDesSoftware = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jButtonAnalytics = new javax.swing.JButton();
        jToggleButtonAyuda = new javax.swing.JToggleButton();
        jToggleButtonAcerca = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPaneFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonEstudiantes.setBackground(new java.awt.Color(1, 45, 151));
        jButtonEstudiantes.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButtonEstudiantes.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEstudiantes.setText("Estudiantes");
        jButtonEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEstudiantesActionPerformed(evt);
            }
        });
        jDesktopPaneFondo.add(jButtonEstudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 162, 57));

        jButtonactuarios.setBackground(new java.awt.Color(0, 24, 82));
        jButtonactuarios.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButtonactuarios.setForeground(new java.awt.Color(255, 255, 255));
        jButtonactuarios.setText("Actuarios");
        jDesktopPaneFondo.add(jButtonactuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 260, 57));
        jButtonactuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActuariosActionPerformed(evt);
            }
        });

        jButtonLicCienciasComputacion.setBackground(new java.awt.Color(0, 37, 126));
        jButtonLicCienciasComputacion.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButtonLicCienciasComputacion.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLicCienciasComputacion.setText("Ciencias de la computacion");
        jButtonLicCienciasComputacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLicCienciasComputacionActionPerformed(evt);
            }
        });
        jDesktopPaneFondo.add(jButtonLicCienciasComputacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 210, 57));

        jButtonlicIngDesSoftware.setBackground(new java.awt.Color(0, 30, 101));
        jButtonlicIngDesSoftware.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButtonlicIngDesSoftware.setForeground(new java.awt.Color(255, 255, 255));
        jButtonlicIngDesSoftware.setText("Ing. en desarrollo de Software");
        jButtonlicIngDesSoftware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonlicIngDesSoftwareActionPerformed(evt);
            }
        });
        jDesktopPaneFondo.add(jButtonlicIngDesSoftware, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 240, 57));

        jLabelTitulo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("MENÚ PRINCIPAL");
        jDesktopPaneFondo.add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 330, -1));

        jButtonAnalytics.setBackground(new java.awt.Color(0, 16, 56));
        jButtonAnalytics.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jButtonAnalytics.setForeground(new java.awt.Color(255, 255, 255));
        //jButtonAnalytics.setText("ANALYTICS");
        //jDesktopPaneFondo.add(jButtonAnalytics, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 500, 320, 80));

        jToggleButtonAyuda.setBackground(new java.awt.Color(0, 79, 237));
        jToggleButtonAyuda.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jToggleButtonAyuda.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButtonAyuda.setText("Ayuda");
        jToggleButtonAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonAyudaActionPerformed(evt);
            }
        });
        jDesktopPaneFondo.add(jToggleButtonAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 70, -1));

        jToggleButtonAcerca.setBackground(new java.awt.Color(0, 79, 237));
        jToggleButtonAcerca.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jToggleButtonAcerca.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButtonAcerca.setText("Acerca de");
        jToggleButtonAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonAcercaActionPerformed(evt);
            }
        });
        jDesktopPaneFondo.add(jToggleButtonAcerca, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 90, -1));

        getContentPane().add(jDesktopPaneFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonlicIngDesSoftwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonlicIngDesSoftwareActionPerformed
        // TODO add your handling code here:
        new JFrameValidacionIngreso().setVisible(true);
    }//GEN-LAST:event_jButtonlicIngDesSoftwareActionPerformed

    private void jButtonEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEstudiantesActionPerformed
       new JFrameValidacionIngreso().setVisible(true);
    }//GEN-LAST:event_jButtonEstudiantesActionPerformed

    private void jToggleButtonAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonAyudaActionPerformed
        new JFrameAyuda().setVisible(true);
    }//GEN-LAST:event_jToggleButtonAyudaActionPerformed

    private void jToggleButtonAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonAcercaActionPerformed
       new JFrameAcercaDe().setVisible(true);
    }//GEN-LAST:event_jToggleButtonAcercaActionPerformed

    private void jButtonLicCienciasComputacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLicCienciasComputacionActionPerformed
         new JFrameValidacionIngreso().setVisible(true);
    }//GEN-LAST:event_jButtonLicCienciasComputacionActionPerformed
    private void jButtonActuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLicCienciasComputacionActionPerformed
        new JFrameValidacionIngreso().setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameGestorEstudiantes_app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameGestorEstudiantes_app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameGestorEstudiantes_app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameGestorEstudiantes_app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameGestorEstudiantes_app().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonlicIngDesSoftware;
    private javax.swing.JButton jButtonAnalytics;
    private javax.swing.JButton jButtonactuarios;
    private javax.swing.JButton jButtonEstudiantes;
    private javax.swing.JButton jButtonLicCienciasComputacion;
    private javax.swing.JDesktopPane jDesktopPaneFondo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JToggleButton jToggleButtonAcerca;
    private javax.swing.JToggleButton jToggleButtonAyuda;
    // End of variables declaration//GEN-END:variables
}
