/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage.gui.menuInicial;

import mypackage.connector.LocalConnector;
import mypackage.entities.Student;
import mypackage.gui.utils.JFrameValidacionIngreso;
import mypackage.gui.otros.JFrameAcercaDe;
import mypackage.gui.otros.JFrameAyuda;
import mypackage.repositories.interfaces.I_StudentRepository;
import mypackage.repositories.jdbc.StudentRepository;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.stream.Stream;

/**
 *
 * @author andres
 */
public class JFrameGestorStudents_app extends javax.swing.JFrame {
    
    
      I_StudentRepository studentRepository = new StudentRepository(LocalConnector.getLocalConnection()) {
          @Override
          public Stream<Student> getStream() {
              return super.getStream();
          }
      };


    /** Creates new form JFrameGestorEmpleados_app */
    public JFrameGestorStudents_app() throws SQLException {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneFondo = new JDesktopPane();
        jButtonStudents = new JButton();
        jButtonDesarrolladores = new JButton();
        jButtonSoporteTecnico = new JButton();
        jButtonAdministracion = new JButton();
        jLabelTitulo = new JLabel();
        jButtonAnalytics = new JButton();
        jToggleButtonAyuda = new JToggleButton();
        jToggleButtonAcerca = new JToggleButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new AbsoluteLayout());

        jDesktopPaneFondo.setLayout(new AbsoluteLayout());

        jButtonStudents.setBackground(new Color(1, 45, 151));
        jButtonStudents.setFont(new Font("Arial", 3, 18)); // NOI18N
        jButtonStudents.setForeground(new Color(255, 255, 255));
        jButtonStudents.setText("ESTUDIANTES");
        jButtonStudents.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButtonStudentsActionPerformed(evt);
            }
        });
        jDesktopPaneFondo.add(jButtonStudents, new AbsoluteConstraints(175, 160, 200, 57));

        jButtonDesarrolladores.setBackground(new Color(0, 24, 82));
        jButtonDesarrolladores.setFont(new Font("Arial", 3, 18)); // NOI18N
        jButtonDesarrolladores.setForeground(new Color(255, 255, 255));
        jButtonDesarrolladores.setText("DESARROLLADORES");
        jDesktopPaneFondo.add(jButtonDesarrolladores, new AbsoluteConstraints(150, 420, 260, 57));

        jButtonSoporteTecnico.setBackground(new Color(0, 37, 126));
        jButtonSoporteTecnico.setFont(new Font("Arial", 3, 18)); // NOI18N
        jButtonSoporteTecnico.setForeground(new Color(255, 255, 255));
        jButtonSoporteTecnico.setText("SOPORTE TECNICO");
        jButtonSoporteTecnico.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButtonSoporteTecnicoActionPerformed(evt);
            }
        });
        jDesktopPaneFondo.add(jButtonSoporteTecnico, new AbsoluteConstraints(155, 240, 250, 57));

        jButtonAdministracion.setBackground(new Color(0, 30, 101));
        jButtonAdministracion.setFont(new Font("Arial", 3, 18)); // NOI18N
        jButtonAdministracion.setForeground(new Color(255, 255, 255));
        jButtonAdministracion.setText("ADMINISTRACION");
        jButtonAdministracion.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButtonAdministracionActionPerformed(evt);
            }
        });
        jDesktopPaneFondo.add(jButtonAdministracion, new AbsoluteConstraints(160, 330, 240, 57));

        jLabelTitulo.setFont(new Font("Arial", 1, 36)); // NOI18N
        jLabelTitulo.setForeground(new Color(255, 255, 255));
        jLabelTitulo.setText("MENÚ PRINCIPAL");
        jDesktopPaneFondo.add(jLabelTitulo, new AbsoluteConstraints(120, 50, 400, -1));

        jButtonAnalytics.setBackground(new Color(0, 16, 56));
        jButtonAnalytics.setFont(new Font("Arial", 1, 20)); // NOI18N
        jButtonAnalytics.setForeground(new Color(255, 255, 255));
        jButtonAnalytics.setText("ANALYTICS");
        jDesktopPaneFondo.add(jButtonAnalytics, new AbsoluteConstraints(120, 500, 320, 80));

        jToggleButtonAyuda.setBackground(new Color(0, 79, 237));
        jToggleButtonAyuda.setFont(new Font("Arial Narrow", 1, 14)); // NOI18N
        jToggleButtonAyuda.setForeground(new Color(255, 255, 255));
        jToggleButtonAyuda.setText("Ayuda");
        jToggleButtonAyuda.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jToggleButtonAyudaActionPerformed(evt);
            }
        });
        jDesktopPaneFondo.add(jToggleButtonAyuda, new AbsoluteConstraints(10, 0, 110, -1));

        jToggleButtonAcerca.setBackground(new Color(0, 79, 237));
        jToggleButtonAcerca.setFont(new Font("Arial Narrow", 1, 14)); // NOI18N
        jToggleButtonAcerca.setForeground(new Color(255, 255, 255));
        jToggleButtonAcerca.setText("Acerca de");
        jToggleButtonAcerca.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jToggleButtonAcercaActionPerformed(evt);
            }
        });
        jDesktopPaneFondo.add(jToggleButtonAcerca, new AbsoluteConstraints(440, 0, 110, -1));

        getContentPane().add(jDesktopPaneFondo, new AbsoluteConstraints(0, 0, 560, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAdministracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdministracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAdministracionActionPerformed

    private void jButtonStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmpleadosActionPerformed
       new JFrameValidacionIngreso().setVisible(true);
    }//GEN-LAST:event_jButtonEmpleadosActionPerformed

    private void jToggleButtonAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonAyudaActionPerformed
        new JFrameAyuda().setVisible(true);
    }//GEN-LAST:event_jToggleButtonAyudaActionPerformed

    private void jToggleButtonAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonAcercaActionPerformed
       new JFrameAcercaDe().setVisible(true);
    }//GEN-LAST:event_jToggleButtonAcercaActionPerformed

    private void jButtonSoporteTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSoporteTecnicoActionPerformed
         new JFrameValidacionIngreso().setVisible(true);
    }//GEN-LAST:event_jButtonSoporteTecnicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameGestorStudents_app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameGestorStudents_app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameGestorStudents_app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameGestorStudents_app.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JFrameGestorStudents_app().setVisible(true);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdministracion;
    private javax.swing.JButton jButtonAnalytics;
    private javax.swing.JButton jButtonDesarrolladores;
    private javax.swing.JButton jButtonStudents;
    private javax.swing.JButton jButtonSoporteTecnico;
    private javax.swing.JDesktopPane jDesktopPaneFondo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JToggleButton jToggleButtonAcerca;
    private javax.swing.JToggleButton jToggleButtonAyuda;
    // End of variables declaration//GEN-END:variables
}
