/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage.gui.estudiantes;
import mypackage.entities.Estudiante;
import mypackage.repositories.interfaces.I_EstudianteRepository;
import mypackage.repositories.jdbc.EstudianteRepository;

import javax.swing.*;
import java.sql.Connection;

/**
 *
 * @author andre
 */
public class JFrameIngresoEstudiante extends javax.swing.JFrame {

    private EstudianteRepository estudiantes;

    /** Creates new form JFrameEmpleados */
    public JFrameIngresoEstudiante() {
        initComponents();
      //  estudiantes = new EstudianteRepository(new Connection().getConnection());

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelMatricula = new javax.swing.JLabel();
        jTextFieldMatricula = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelApellido = new javax.swing.JLabel();
        jTextFieldApellido = new javax.swing.JTextField();
        jLabelEdad = new javax.swing.JLabel();
        jTextFieldEdad = new javax.swing.JTextField();
        jLabelGenero = new javax.swing.JLabel();
        jTextFieldGenero = new javax.swing.JTextField();
        jLabelTipoEstudiante = new javax.swing.JLabel();
        jTextFieldModalidad = new javax.swing.JTextField();
        jLabelModalidad = new javax.swing.JLabel();
        jTextFieldPromedioIngreso = new javax.swing.JTextField();
        jLabelPromedioIngreso = new javax.swing.JLabel();
        jTextFieldTipoEstudiante = new javax.swing.JTextField();
        jLabelCorreo3 = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jTextFieldCorreoElectronico = new javax.swing.JTextField();
        jLabelDomicilio = new javax.swing.JLabel();
        jTextFieldNumeroTelefono = new javax.swing.JTextField();
        jTextFieldDomicilio = new javax.swing.JTextField();
        jLabelAnioIngreso = new javax.swing.JLabel();
        jTextFieldAnioIngreso = new javax.swing.JTextField();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonAgregar = new javax.swing.JButton();
        jButtonAgregar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("INGRESAR ESTUDIANTE");
        jDesktopPane1.add(jLabelTitulo);
        jLabelTitulo.setBounds(120, 20, 430, 42);



        //MATRICULA
        jLabelMatricula.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelMatricula.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMatricula.setText("Matricula:");
        jDesktopPane1.add(jLabelMatricula);
        jLabelMatricula.setBounds(160, 110, 98, 20);

        jTextFieldMatricula.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jDesktopPane1.add(jTextFieldMatricula);
        jTextFieldMatricula.setBounds(260, 110, 191, 28);

        //NOMBRE
        jLabelNombre.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setText("Nombre:");
        jDesktopPane1.add(jLabelNombre);
        jLabelNombre.setBounds(170, 150, 98, 20);

        jTextFieldNombre.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jDesktopPane1.add(jTextFieldNombre);
        jTextFieldNombre.setBounds(260, 150, 191, 28);
//APELLIDO
        jLabelApellido.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelApellido.setForeground(new java.awt.Color(255, 255, 255));
        jLabelApellido.setText("Apellido:");
        jDesktopPane1.add(jLabelApellido);
        jLabelApellido.setBounds(170, 190, 104, 20);

        jTextFieldApellido.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jDesktopPane1.add(jTextFieldApellido);
        jTextFieldApellido.setBounds(260, 190, 191, 28);


//EDAD
        jLabelEdad.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelEdad.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEdad.setText("Edad:");
        jDesktopPane1.add(jLabelEdad);
        jLabelEdad.setBounds(200, 230, 55, 20);

        jTextFieldEdad.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jDesktopPane1.add(jTextFieldEdad);
        jTextFieldEdad.setBounds(260, 230, 191, 28);

//GENERO
        jLabelGenero.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelGenero.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGenero.setText("Genero:");
        jDesktopPane1.add(jLabelGenero);
        jLabelGenero.setBounds(180, 270, 100, 20);

        jTextFieldGenero.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jDesktopPane1.add(jTextFieldGenero);
        jTextFieldGenero.setBounds(260, 270, 191, 28);

        //MODALIDAD
        jLabelModalidad.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelModalidad.setForeground(new java.awt.Color(255, 255, 255));
        jLabelModalidad.setText("Modalidad:");
        jDesktopPane1.add(jLabelModalidad);
        jLabelModalidad.setBounds(150, 310, 120, 20);

        jTextFieldModalidad.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jDesktopPane1.add(jTextFieldModalidad);
        jTextFieldModalidad.setBounds(260, 310, 191, 28);

//TIPO ESTUDIANTE
        jLabelTipoEstudiante.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelTipoEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTipoEstudiante.setText("Tipo Estudiante:");
        jDesktopPane1.add(jLabelTipoEstudiante);
        jLabelTipoEstudiante.setBounds(90, 350, 180, 20);

        jTextFieldTipoEstudiante.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jDesktopPane1.add(jTextFieldTipoEstudiante);
        jTextFieldTipoEstudiante.setBounds(260, 350, 191, 28);

//CORREO
        jLabelCorreo3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelCorreo3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCorreo3.setText("Correo:");
        jDesktopPane1.add(jLabelCorreo3);
        jLabelCorreo3.setBounds(180, 390, 100, 20);

        jTextFieldCorreoElectronico.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jDesktopPane1.add(jTextFieldCorreoElectronico);
        jTextFieldCorreoElectronico.setBounds(260, 390, 191, 28);


//TELEFONO
        jLabelTelefono.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelTelefono.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTelefono.setText("Telefono:");
        jDesktopPane1.add(jLabelTelefono);
        jLabelTelefono.setBounds(160, 430, 130, 20);

        jTextFieldNumeroTelefono.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jDesktopPane1.add(jTextFieldNumeroTelefono);
        jTextFieldNumeroTelefono.setBounds(260, 430, 191, 28);


//DOMICILIO
        jLabelDomicilio.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelDomicilio.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDomicilio.setText("Domicilio:");
        jDesktopPane1.add(jLabelDomicilio);
        jLabelDomicilio.setBounds(160, 470, 100, 20);

        jTextFieldDomicilio.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jDesktopPane1.add(jTextFieldDomicilio);
        jTextFieldDomicilio.setBounds(260, 470, 191, 28);


//ANIO INGRESO
        jLabelAnioIngreso.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelAnioIngreso.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAnioIngreso.setText("Año Ingreso:");
        jDesktopPane1.add(jLabelAnioIngreso);
        jLabelAnioIngreso.setBounds(120, 510, 180, 20);

        jTextFieldAnioIngreso.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jDesktopPane1.add(jTextFieldAnioIngreso);
        jTextFieldAnioIngreso.setBounds(260, 510, 191, 28);


//PROMEDIO INGRESO
        jLabelPromedioIngreso.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelPromedioIngreso.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPromedioIngreso.setText("Promedio Ingreso:");
        jDesktopPane1.add(jLabelPromedioIngreso);
        jLabelPromedioIngreso.setBounds(75, 550, 180, 20);

        jTextFieldPromedioIngreso.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jDesktopPane1.add(jTextFieldPromedioIngreso);
        jTextFieldPromedioIngreso.setBounds(260, 550, 191, 28);


        jButtonLimpiar.setBackground(new java.awt.Color(0, 32, 108));
        jButtonLimpiar.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButtonLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLimpiar.setText("Limpiar ");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButtonLimpiar);
        jButtonLimpiar.setBounds(70, 590, 142, 30);

        jButtonAgregar.setBackground(new java.awt.Color(0, 32, 108));
        jButtonAgregar.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButtonAgregar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButtonAgregar);
        jButtonAgregar.setBounds(420, 590, 140, 30);

        jButtonAgregar1.setBackground(new java.awt.Color(1, 26, 86));
        jButtonAgregar1.setFont(new java.awt.Font("Arial", 3, 17)); // NOI18N
        jButtonAgregar1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAgregar1.setText("LISTA DE ESTUDIANTES");
        jButtonAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregar1ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButtonAgregar1);
        jButtonAgregar1.setBounds(190, 615, 240, 30);

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 870));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed

        jTextFieldMatricula.setText("");
        jTextFieldNombre.setText("");
        jTextFieldApellido.setText("");
        jTextFieldAnioIngreso.setText("");
        jTextFieldCorreoElectronico.setText("");
        jTextFieldEdad.setText("");
        jTextFieldDomicilio.setText("");
        jTextFieldGenero.setText("");
        jTextFieldTipoEstudiante.setText("");
        jTextFieldNumeroTelefono.setText("");
        jTextFieldPromedioIngreso.setText("");
        jTextFieldModalidad.setText("");
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
            try {
                int matricula = Integer.parseInt(jTextFieldMatricula.getText());
                String nombre = jTextFieldNombre.getText();
                String apellido = jTextFieldApellido.getText();
                int edad = Integer.parseInt(jTextFieldEdad.getText());
                String genero = jTextFieldGenero.getText();
                String modalidad = jTextFieldModalidad.getText();
                String tipoEstudiante = jTextFieldTipoEstudiante.getText();
                String correo = jTextFieldCorreoElectronico.getText();
                String telefono = jTextFieldNumeroTelefono.getText();
                String domicilio = jTextFieldDomicilio.getText();
                int anioIngreso = Integer.parseInt(jTextFieldAnioIngreso.getText());
                float promedioIngreso = Float.parseFloat(jTextFieldPromedioIngreso.getText());

                //crear un objeto estudiante con los datos de los campos ingresados
                Estudiante nuevo = new Estudiante(matricula, nombre, apellido, edad, genero, modalidad, tipoEstudiante, correo, telefono, domicilio, anioIngreso, promedioIngreso);

                //utilizar el estudiante repository para guardar los datos en la base de datos
                estudiantes.save(nuevo);

                JOptionPane.showMessageDialog(this, "Estudiante agregado correctamente.");

                jButtonLimpiar.doClick(); // Limpiar campos si tienes ese botón

            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error al agregar estudiante:\n" + e.getMessage());
            }
        }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregar1ActionPerformed
       new JFrameVerEstudiante().setVisible(true);
    }//GEN-LAST:event_jButtonAgregar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameIngresoEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameIngresoEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameIngresoEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameIngresoEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameIngresoEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonAgregar1;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelMatricula;
    private javax.swing.JLabel jLabelAnioIngreso;
    private javax.swing.JLabel jLabelCorreo3;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JLabel jLabelDomicilio;
    private javax.swing.JLabel jLabelGenero;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTipoEstudiante;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelPromedioIngreso;
    private javax.swing.JLabel jLabelModalidad;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldAnioIngreso;
    private javax.swing.JTextField jTextFieldCorreoElectronico;
    private javax.swing.JTextField jTextFieldEdad;
    private javax.swing.JTextField jTextFieldDomicilio;
    private javax.swing.JTextField jTextFieldGenero;
    private javax.swing.JTextField jTextFieldMatricula;
    private javax.swing.JTextField jTextFieldTipoEstudiante;
    private javax.swing.JTextField jTextFieldNumeroTelefono;
    private javax.swing.JTextField jTextFieldPromedioIngreso;
    private javax.swing.JTextField jTextFieldModalidad;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
