/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage.gui.Estudiantes;

/**
 *
 * @author andre
 */
public class JFrameIngresoAlumno extends javax.swing.JFrame {

    /** Creates new form JFrameAlumnos */
    public JFrameIngresoAlumno() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelApellido = new javax.swing.JLabel();
        jTextFieldApellido = new javax.swing.JTextField();
        jLabelEdad = new javax.swing.JLabel();
        jTextFieldEdad = new javax.swing.JTextField();
        jLabelGenero = new javax.swing.JLabel();
        jTextFieldGenero = new javax.swing.JTextField();
        jTextFieldSueldo = new javax.swing.JTextField();
        jLabelNumDoc2 = new javax.swing.JLabel();
        jLabelCorreo1 = new javax.swing.JLabel();
        jTextFieldSemestre = new javax.swing.JTextField();
        jLabelTipoDoc3 = new javax.swing.JLabel();
        jLabelTipoDoc4 = new javax.swing.JLabel();
        jLabelNumDoc3 = new javax.swing.JLabel();
        jLabelSueldo = new javax.swing.JLabel();
        jTextFieldMatricula = new javax.swing.JTextField();
        jLabelCorreo3 = new javax.swing.JLabel();
        jLabelNumero2 = new javax.swing.JLabel();
        jTextFieldCorreoElectronico = new javax.swing.JTextField();
        jLabelNumero3 = new javax.swing.JLabel();
        jLabelFecha2 = new javax.swing.JLabel();
        jTextFieldNumeroTelefono = new javax.swing.JTextField();
        jLabelFecha3 = new javax.swing.JLabel();
        jLabelCantidadHs1 = new javax.swing.JLabel();
        jTextFieldIniciodelSemestre = new javax.swing.JTextField();
        jLabelCantidadHs3 = new javax.swing.JLabel();
        jTextFieldFindelSemestre = new javax.swing.JTextField();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonAgregar = new javax.swing.JButton();
        jButtonAgregar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitulo.setText("INGRESAR ALUMNO");
        jDesktopPane1.add(jLabelTitulo);
        jLabelTitulo.setBounds(150, 20, 430, 42);

        jLabelNombre.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNombre.setText("Nombre:");
        jDesktopPane1.add(jLabelNombre);
        jLabelNombre.setBounds(175, 80, 98, 28);

        jTextFieldNombre.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldNombre);
        jTextFieldNombre.setBounds(275, 80, 191, 34);

        jLabelApellido.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelApellido.setForeground(new java.awt.Color(0, 0, 0));
        jLabelApellido.setText("Apellido:");
        jDesktopPane1.add(jLabelApellido);
        jLabelApellido.setBounds(175, 130, 98, 28);

        jTextFieldApellido.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldApellido);
        jTextFieldApellido.setBounds(275, 130, 191, 34);

        jLabelEdad.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelEdad.setForeground(new java.awt.Color(0, 0, 0));
        jLabelEdad.setText("Edad:");
        jDesktopPane1.add(jLabelEdad);
        jLabelEdad.setBounds(175, 180, 98, 28);

        jTextFieldEdad.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldEdad);
        jTextFieldEdad.setBounds(275, 180, 191, 34);

        jLabelGenero.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelGenero.setForeground(new java.awt.Color(0, 0, 0));
        jLabelGenero.setText("Genero:");
        jDesktopPane1.add(jLabelGenero);
        jLabelGenero.setBounds(175, 230, 98, 28);

        jTextFieldGenero.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldGenero);
        jTextFieldGenero.setBounds(275, 230, 191, 34);

        jLabelCorreo3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelCorreo3.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCorreo3.setText("Correo:");
        jDesktopPane1.add(jLabelCorreo3);
        jLabelCorreo3.setBounds(175, 280, 98, 28);

        jTextFieldCorreoElectronico.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldCorreoElectronico);
        jTextFieldCorreoElectronico.setBounds(275, 280, 191, 34);

        jLabelNumero2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelNumero2.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNumero2.setText("Telefono:");
        jDesktopPane1.add(jLabelNumero2);
        jLabelNumero2.setBounds(175, 330, 98, 28);

        jTextFieldNumeroTelefono.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldNumeroTelefono);
        jTextFieldNumeroTelefono.setBounds(275, 330, 191, 34);

        jLabelNumDoc2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelNumDoc2.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNumDoc2.setText("Semestre:");
        jDesktopPane1.add(jLabelNumDoc2);
        jLabelNumDoc2.setBounds(175, 380, 98, 28);

        jTextFieldSemestre.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldSemestre);
        jTextFieldSemestre.setBounds(275, 380, 191, 34);

        jLabelNumDoc3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelNumDoc3.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNumDoc3.setText("Matricula:");
        jDesktopPane1.add(jLabelNumDoc3);
        jLabelNumDoc3.setBounds(175, 430, 98, 28);

        jTextFieldMatricula.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldMatricula);
        jTextFieldMatricula.setBounds(275, 430, 191, 34);

        jLabelFecha3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelFecha3.setForeground(new java.awt.Color(0, 0, 0));
        jLabelFecha3.setText("Inicio del ");
        jDesktopPane1.add(jLabelFecha3);
        jLabelFecha3.setBounds(175, 480, 98, 28);

        jLabelFecha2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelFecha2.setForeground(new java.awt.Color(0, 0, 0));
        jLabelFecha2.setText("semestre:");
        jDesktopPane1.add(jLabelFecha2);
        jLabelFecha2.setBounds(175, 500, 191, 34);

        jTextFieldIniciodelSemestre.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldIniciodelSemestre);
        jTextFieldIniciodelSemestre.setBounds(275, 490, 191, 34);

        jLabelTipoDoc3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelTipoDoc3.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTipoDoc3.setText("Fin del");
        jDesktopPane1.add(jLabelTipoDoc3);
        jLabelTipoDoc3.setBounds(175, 540, 98, 28);

        jLabelTipoDoc4.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelTipoDoc4.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTipoDoc4.setText("Semestre:");
        jDesktopPane1.add(jLabelTipoDoc4);
        jLabelTipoDoc4.setBounds(175, 560, 191, 34);

        jTextFieldFindelSemestre.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldFindelSemestre);
        jTextFieldFindelSemestre.setBounds(275, 550, 191, 34);

       /*
       jLabelCorreo1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelCorreo1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCorreo1.setText("electrónico:");
        jDesktopPane1.add(jLabelCorreo1);
        jLabelCorreo1.setBounds(150, 420, 120, 40);

       jTextFieldSueldo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldSueldo);
        jTextFieldSueldo.setBounds(270, 660, 191, 34);

        jLabelSueldo.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelSueldo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSueldo.setText("Sueldo:");
        jDesktopPane1.add(jLabelSueldo);
        jLabelSueldo.setBounds(200, 660, 80, 40);


        jLabelNumero3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelNumero3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumero3.setText("Numero ");
        jDesktopPane1.add(jLabelNumero3);
        jLabelNumero3.setBounds(170, 460, 110, 40);

        jLabelCantidadHs1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelCantidadHs1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCantidadHs1.setText("Cantidad hs");
        jDesktopPane1.add(jLabelCantidadHs1);
        jLabelCantidadHs1.setBounds(150, 580, 120, 40);

        jLabelCantidadHs3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelCantidadHs3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCantidadHs3.setText("semanales:");
        jDesktopPane1.add(jLabelCantidadHs3);
        jLabelCantidadHs3.setBounds(160, 600, 110, 40);

        */

        jButtonLimpiar.setBackground(new java.awt.Color(104, 140, 255));
        jButtonLimpiar.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButtonLimpiar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonLimpiar.setText("Limpiar ");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButtonLimpiar);
        jButtonLimpiar.setBounds(170, 600, 142, 50);

        jButtonAgregar.setBackground(new java.awt.Color(104, 140, 255));
        jButtonAgregar.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButtonAgregar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButtonAgregar);
        jButtonAgregar.setBounds(340, 600, 140, 50);

        jButtonAgregar1.setBackground(new java.awt.Color(90, 120, 255));
        jButtonAgregar1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButtonAgregar1.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAgregar1.setText("LISTA DE ALUMNOS");
        jButtonAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregar1ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButtonAgregar1);
        jButtonAgregar1.setBounds(70, 670, 520, 60);

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 870));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed

        jTextFieldNombre.setText("");
        jTextFieldApellido.setText("");
        jTextFieldFindelSemestre.setText("");
        jTextFieldCorreoElectronico.setText("");
        jTextFieldEdad.setText("");
        jTextFieldIniciodelSemestre.setText("");
        jTextFieldGenero.setText("");
        jTextFieldMatricula.setText("");
        jTextFieldNumeroTelefono.setText("");
        jTextFieldSueldo.setText("");
        jTextFieldSemestre.setText("");
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregar1ActionPerformed
       new JFrameVerAlumno().setVisible(true);
    }//GEN-LAST:event_jButtonAgregar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameIngresoAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameIngresoAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameIngresoAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameIngresoAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameIngresoAlumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonAgregar1;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelCantidadHs1;
    private javax.swing.JLabel jLabelCantidadHs3;
    private javax.swing.JLabel jLabelCorreo1;
    private javax.swing.JLabel jLabelCorreo3;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JLabel jLabelFecha2;
    private javax.swing.JLabel jLabelFecha3;
    private javax.swing.JLabel jLabelGenero;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNumDoc2;
    private javax.swing.JLabel jLabelNumDoc3;
    private javax.swing.JLabel jLabelNumero2;
    private javax.swing.JLabel jLabelNumero3;
    private javax.swing.JLabel jLabelSueldo;
    private javax.swing.JLabel jLabelTipoDoc3;
    private javax.swing.JLabel jLabelTipoDoc4;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldFindelSemestre;
    private javax.swing.JTextField jTextFieldCorreoElectronico;
    private javax.swing.JTextField jTextFieldEdad;
    private javax.swing.JTextField jTextFieldIniciodelSemestre;
    private javax.swing.JTextField jTextFieldGenero;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldMatricula;
    private javax.swing.JTextField jTextFieldNumeroTelefono;
    private javax.swing.JTextField jTextFieldSueldo;
    private javax.swing.JTextField jTextFieldSemestre;
    // End of variables declaration//GEN-END:variables
}
