/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage.gui.Estudiantes;

/**
 *
 * @author andre
 */
public class JFrameActualizarEstudiante extends javax.swing.JFrame {

    /** Creates new form JFrameActualizarEstudiantes */
    public JFrameActualizarEstudiante() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelApellido = new javax.swing.JLabel();
        jTextFieldApellido = new javax.swing.JTextField();
        jLabelEdad = new javax.swing.JLabel();
        jTextFieldEdad = new javax.swing.JTextField();
        jLabelGenero = new javax.swing.JLabel();
        jTextFieldGenero = new javax.swing.JTextField();
        jTextFieldSemestre = new javax.swing.JTextField();
        jLabelNumDoc2 = new javax.swing.JLabel();
        jLabelCorreo1 = new javax.swing.JLabel();
        jTextFieldCorreo = new javax.swing.JTextField();
        jLabelTipoDoc3 = new javax.swing.JLabel();
        jLabelTipoDoc4 = new javax.swing.JLabel();
        jLabelNumDoc3 = new javax.swing.JLabel();
        jLabelSueldo = new javax.swing.JLabel();
        jTextFieldMatricula = new javax.swing.JTextField();
        jLabelCorreo3 = new javax.swing.JLabel();
        jLabelNumero2 = new javax.swing.JLabel();
        jTextFieldCorreoElectronico = new javax.swing.JTextField();
        jLabelNumero3 = new javax.swing.JLabel();
        jLabelFecha2 = new javax.swing.JLabel();
        jTextFieldNumeroTelefono = new javax.swing.JTextField();
        jLabelFecha3 = new javax.swing.JLabel();
        jLabelCantidadHs1 = new javax.swing.JLabel();
        jTextFieldInicio_Semestre = new javax.swing.JTextField();
        jLabelCantidadHs3 = new javax.swing.JLabel();
        jTextFieldFin_Semestre = new javax.swing.JTextField();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonActualizar = new javax.swing.JButton();
        jButtonAgregar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitulo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitulo.setText("ACTUALIZACIÓN DE ALUMNOS");
        jDesktopPane1.add(jLabelTitulo);
        jLabelTitulo.setBounds(40, 30, 610, 42);

        jLabelNombre.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNombre.setText("Nombre:");
        jDesktopPane1.add(jLabelNombre);
        jLabelNombre.setBounds(150, 90, 98, 28);

        jTextFieldNombre.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldNombre);
        jTextFieldNombre.setBounds(245, 90, 195, 34);

        jLabelApellido.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelApellido.setForeground(new java.awt.Color(0, 0, 0));
        jLabelApellido.setText("Apellido:");
        jDesktopPane1.add(jLabelApellido);
        jLabelApellido.setBounds(150, 140, 98, 28);

        jTextFieldApellido.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldApellido);
        jTextFieldApellido.setBounds(245, 140, 195, 34);

        jLabelEdad.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelEdad.setForeground(new java.awt.Color(0, 0, 0));
        jLabelEdad.setText("Edad:");
        jDesktopPane1.add(jLabelEdad);
        jLabelEdad.setBounds(150, 190, 98, 28);

        jTextFieldEdad.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldEdad);
        jTextFieldEdad.setBounds(245, 190, 195, 34);

        jLabelGenero.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelGenero.setForeground(new java.awt.Color(0, 0, 0));
        jLabelGenero.setText("Genero:");
        jDesktopPane1.add(jLabelGenero);
        jLabelGenero.setBounds(150, 240, 98, 28);

        jTextFieldGenero.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldGenero);
        jTextFieldGenero.setBounds(245, 240, 195, 34);

        jLabelTipoDoc3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelTipoDoc3.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTipoDoc3.setText("Telefono:");
        jDesktopPane1.add(jLabelTipoDoc3);
        jLabelTipoDoc3.setBounds(150, 290, 98, 28);

        jTextFieldNumeroTelefono.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldNumeroTelefono);
        jTextFieldNumeroTelefono.setBounds(245, 290, 195, 34);

       /* jLabelNumero2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelNumero2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumero2.setText("de telefono:");
        jDesktopPane1.add(jLabelNumero2);
        jLabelNumero2.setBounds(140, 430, 130, 40);*/

       /* jLabelNumero3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelNumero3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumero3.setText("Numero ");
        jDesktopPane1.add(jLabelNumero3);
        jLabelNumero3.setBounds(160, 410, 110, 40);*/

        jLabelCorreo1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelCorreo1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCorreo1.setText("Correo:");
        jDesktopPane1.add(jLabelCorreo1);
        jLabelCorreo1.setBounds(150, 340, 98, 28);

        jTextFieldCorreo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldCorreo);
        jTextFieldCorreo.setBounds(245, 340, 195, 34);

       /* jLabelCorreo3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelCorreo3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCorreo3.setText("Correo");
        jDesktopPane1.add(jLabelCorreo3);
        jLabelCorreo3.setBounds(170, 350, 70, 40);

        jTextFieldCorreoElectronico.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldCorreoElectronico);
        jTextFieldCorreoElectronico.setBounds(260, 370, 191, 34);*/


        jLabelNumDoc2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelNumDoc2.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNumDoc2.setText("Semestre:");
        jDesktopPane1.add(jLabelNumDoc2);
        jLabelNumDoc2.setBounds(150, 390, 98, 28);

        jTextFieldSemestre.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldSemestre);
        jTextFieldSemestre.setBounds(245, 390, 195, 34);


        jLabelTipoDoc4.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelTipoDoc4.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTipoDoc4.setText("Matricula:");
        jDesktopPane1.add(jLabelTipoDoc4);
        jLabelTipoDoc4.setBounds(150, 440, 98, 28);

        jTextFieldMatricula.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldMatricula);
        jTextFieldMatricula.setBounds(245, 440, 195, 34);

       /* jLabelNumDoc3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelNumDoc3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumDoc3.setText("Numero de");
        jDesktopPane1.add(jLabelNumDoc3);
        jLabelNumDoc3.setBounds(140, 290, 110, 30);

        jLabelSueldo.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelSueldo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSueldo.setText("Sueldo:");
        jDesktopPane1.add(jLabelSueldo);
        jLabelSueldo.setBounds(180, 590, 80, 40);*/

        jLabelFecha3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelFecha3.setForeground(new java.awt.Color(0, 0, 0));
        jLabelFecha3.setText("Inicio del");
        jDesktopPane1.add(jLabelFecha3);
        jLabelFecha3.setBounds(150, 490, 98, 28);

        jLabelFecha2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelFecha2.setForeground(new java.awt.Color(0, 0, 0));
        jLabelFecha2.setText("semestre:");
        jDesktopPane1.add(jLabelFecha2);
        jLabelFecha2.setBounds(150, 510, 98, 28);

        jTextFieldInicio_Semestre.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldInicio_Semestre);
        jTextFieldInicio_Semestre.setBounds(245, 500, 195, 34);

        jLabelCantidadHs1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelCantidadHs1.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCantidadHs1.setText("Fin del");
        jDesktopPane1.add(jLabelCantidadHs1);
        jLabelCantidadHs1.setBounds(155, 560, 98, 28);


        jLabelCantidadHs3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelCantidadHs3.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCantidadHs3.setText("semestre:");
        jDesktopPane1.add(jLabelCantidadHs3);
        jLabelCantidadHs3.setBounds(150, 580, 98, 28);

        jTextFieldFin_Semestre.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldFin_Semestre);
        jTextFieldFin_Semestre.setBounds(245, 570, 195, 34);



        jButtonLimpiar.setBackground(new java.awt.Color(104, 140, 255));
        jButtonLimpiar.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButtonLimpiar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonLimpiar.setText(" Limpiar ");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButtonLimpiar);
        jButtonLimpiar.setBounds(100, 650, 142, 50);

        jButtonActualizar.setBackground(new java.awt.Color(104, 140, 255));
        jButtonActualizar.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButtonActualizar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonActualizar.setText(" Actualizar ");
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButtonActualizar);
        jButtonActualizar.setBounds(275, 650, 140, 50);

        jButtonAgregar1.setBackground(new java.awt.Color(104, 140, 255));
        jButtonAgregar1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButtonAgregar1.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAgregar1.setText("Ver Alumnos");
        jButtonAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregar1ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButtonAgregar1);
        jButtonAgregar1.setBounds(450, 650, 180, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed

        jTextFieldNombre.setText("");
        jTextFieldApellido.setText("");
        jTextFieldFin_Semestre.setText("");
        jTextFieldCorreoElectronico.setText("");
        jTextFieldEdad.setText("");
        jTextFieldInicio_Semestre.setText("");
        jTextFieldGenero.setText("");
        jTextFieldMatricula.setText("");
        jTextFieldNumeroTelefono.setText("");
        jTextFieldSemestre.setText("");
        jTextFieldCorreo.setText("");
    }//GEN-LAST:event_jButtonLimpiarActionPerformed


    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonActualizarActionPerformed
   // String nombre = jTextFieldNombre.getText();



    private void jButtonAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAgregar1ActionPerformed



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameActualizarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameActualizarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameActualizarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameActualizarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameActualizarEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonAgregar1;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelCantidadHs1;
    private javax.swing.JLabel jLabelCantidadHs3;
    private javax.swing.JLabel jLabelCorreo1;
    private javax.swing.JLabel jLabelCorreo3;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JLabel jLabelFecha2;
    private javax.swing.JLabel jLabelFecha3;
    private javax.swing.JLabel jLabelGenero;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNumDoc2;
    private javax.swing.JLabel jLabelNumDoc3;
    private javax.swing.JLabel jLabelNumero2;
    private javax.swing.JLabel jLabelNumero3;
    private javax.swing.JLabel jLabelSueldo;
    private javax.swing.JLabel jLabelTipoDoc3;
    private javax.swing.JLabel jLabelTipoDoc4;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldFin_Semestre;
    private javax.swing.JTextField jTextFieldCorreoElectronico;
    private javax.swing.JTextField jTextFieldEdad;
    private javax.swing.JTextField jTextFieldInicio_Semestre;
    private javax.swing.JTextField jTextFieldGenero;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldMatricula;
    private javax.swing.JTextField jTextFieldNumeroTelefono;
    private javax.swing.JTextField jTextFieldSemestre;
    private javax.swing.JTextField jTextFieldCorreo;
    // End of variables declaration//GEN-END:variables
}
