/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage.gui.estudiantes;

/**
 *
 * @author andre
 */
public class JFrameActualizarEstudiante extends javax.swing.JFrame {

    /** Creates new form JFrameActualizarEmpleados */
    public JFrameActualizarEstudiante() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {


        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelMatricula = new javax.swing.JLabel();
        jTextFieldMatricula = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelApellido = new javax.swing.JLabel();
        jTextFieldApellido = new javax.swing.JTextField();
        jLabelEdad = new javax.swing.JLabel();
        jTextFieldEdad = new javax.swing.JTextField();
        jLabelGenero = new javax.swing.JLabel();
        jTextFieldGenero = new javax.swing.JTextField();
        jLabelTipoEstudiante = new javax.swing.JLabel();
        jTextFieldModalidad = new javax.swing.JTextField();
        jLabelModalidad = new javax.swing.JLabel();
        jTextFieldPromedioIngreso = new javax.swing.JTextField();
        jLabelPromedioIngreso = new javax.swing.JLabel();
        jTextFieldTipoEstudiante = new javax.swing.JTextField();
        jLabelCorreo3 = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jTextFieldCorreoElectronico = new javax.swing.JTextField();
        jLabelDomicilio = new javax.swing.JLabel();
        jTextFieldNumeroTelefono = new javax.swing.JTextField();
        jTextFieldDomicilio = new javax.swing.JTextField();
        jLabelAnioIngreso = new javax.swing.JLabel();
        jTextFieldAnioIngreso = new javax.swing.JTextField();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonActualizar = new javax.swing.JButton();
        jButtonVerEstudiante = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitulo.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("ACTUALIZACIÓN DE ESTUDIANTE");
        jDesktopPane1.add(jLabelTitulo);
        jLabelTitulo.setBounds(30, 20, 550, 25);

 //MATRICULA
        jLabelMatricula.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelMatricula.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMatricula.setText("Matricula:");
        jDesktopPane1.add(jLabelMatricula);
        jLabelMatricula.setBounds(160, 120, 98, 20);

        jTextFieldMatricula.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jDesktopPane1.add(jTextFieldMatricula);
        jTextFieldMatricula.setBounds(260, 120, 191, 28);

 //NOMBRE
        jLabelNombre.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setText("Nombre:");
        jDesktopPane1.add(jLabelNombre);
        jLabelNombre.setBounds(170, 160, 98, 20);

        jTextFieldNombre.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jDesktopPane1.add(jTextFieldNombre);
        jTextFieldNombre.setBounds(260, 160, 191, 28);
//APELLIDO
        jLabelApellido.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelApellido.setForeground(new java.awt.Color(255, 255, 255));
        jLabelApellido.setText("Apellido:");
        jDesktopPane1.add(jLabelApellido);
        jLabelApellido.setBounds(170, 200, 104, 20);

        jTextFieldApellido.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jDesktopPane1.add(jTextFieldApellido);
        jTextFieldApellido.setBounds(260, 200, 191, 28);


//EDAD
        jLabelEdad.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelEdad.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEdad.setText("Edad:");
        jDesktopPane1.add(jLabelEdad);
        jLabelEdad.setBounds(200, 240, 55, 20);

        jTextFieldEdad.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jDesktopPane1.add(jTextFieldEdad);
        jTextFieldEdad.setBounds(260, 240, 191, 28);

//GENERO
        jLabelGenero.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelGenero.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGenero.setText("Genero:");
        jDesktopPane1.add(jLabelGenero);
        jLabelGenero.setBounds(180, 280, 100, 20);

        jTextFieldGenero.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jDesktopPane1.add(jTextFieldGenero);
        jTextFieldGenero.setBounds(260, 280, 191, 28);

 //MODALIDAD
        jLabelModalidad.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelModalidad.setForeground(new java.awt.Color(255, 255, 255));
        jLabelModalidad.setText("Modalidad:");
        jDesktopPane1.add(jLabelModalidad);
        jLabelModalidad.setBounds(150, 320, 120, 20);

        jTextFieldModalidad.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jDesktopPane1.add(jTextFieldModalidad);
        jTextFieldModalidad.setBounds(260, 320, 191, 28);

//TIPO ESTUDIANTE
        jLabelTipoEstudiante.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelTipoEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTipoEstudiante.setText("Tipo Estudiante:");
        jDesktopPane1.add(jLabelTipoEstudiante);
        jLabelTipoEstudiante.setBounds(90, 360, 180, 20);

        jTextFieldTipoEstudiante.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jDesktopPane1.add(jTextFieldTipoEstudiante);
        jTextFieldTipoEstudiante.setBounds(260, 360, 191, 28);

//CORREO
        jLabelCorreo3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelCorreo3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCorreo3.setText("Correo:");
        jDesktopPane1.add(jLabelCorreo3);
        jLabelCorreo3.setBounds(180, 400, 100, 20);

        jTextFieldCorreoElectronico.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jDesktopPane1.add(jTextFieldCorreoElectronico);
        jTextFieldCorreoElectronico.setBounds(260, 400, 191, 28);


//TELEFONO
        jLabelTelefono.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelTelefono.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTelefono.setText("Telefono:");
        jDesktopPane1.add(jLabelTelefono);
        jLabelTelefono.setBounds(160, 440, 130, 20);

        jTextFieldNumeroTelefono.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jDesktopPane1.add(jTextFieldNumeroTelefono);
        jTextFieldNumeroTelefono.setBounds(260, 440, 191, 28);


//DOMICILIO
        jLabelDomicilio.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelDomicilio.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDomicilio.setText("Domicilio:");
        jDesktopPane1.add(jLabelDomicilio);
        jLabelDomicilio.setBounds(160, 480, 100, 20);

        jTextFieldDomicilio.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jDesktopPane1.add(jTextFieldDomicilio);
        jTextFieldDomicilio.setBounds(260, 480, 191, 28);


//ANIO INGRESO
        jLabelAnioIngreso.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelAnioIngreso.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAnioIngreso.setText("Año Ingreso:");
        jDesktopPane1.add(jLabelAnioIngreso);
        jLabelAnioIngreso.setBounds(120, 520, 180, 20);

        jTextFieldAnioIngreso.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jDesktopPane1.add(jTextFieldAnioIngreso);
        jTextFieldAnioIngreso.setBounds(260, 520, 191, 28);


//PROMEDIO INGRESO
        jLabelPromedioIngreso.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelPromedioIngreso.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPromedioIngreso.setText("Promedio Ingreso:");
        jDesktopPane1.add(jLabelPromedioIngreso);
        jLabelPromedioIngreso.setBounds(75, 560, 180, 20);

        jTextFieldPromedioIngreso.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jDesktopPane1.add(jTextFieldPromedioIngreso);
        jTextFieldPromedioIngreso.setBounds(260, 560, 191, 28);


    //BOTON LIMPIAR CAMPOS
        jButtonLimpiar.setBackground(new java.awt.Color(0, 32, 108));
        jButtonLimpiar.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButtonLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLimpiar.setText("Limpiar ");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButtonLimpiar);
        jButtonLimpiar.setBounds(80, 600, 142, 30);

    //BOTON ACTUALIZAR
        jButtonActualizar.setBackground(new java.awt.Color(0, 32, 108));
        jButtonActualizar.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButtonActualizar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonActualizar.setText("Actualizar");
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButtonActualizar);
        jButtonActualizar.setBounds(450, 600, 140, 30);

    //BOTON VER ESTUDIANTES
        jButtonVerEstudiante.setBackground(new java.awt.Color(1, 26, 86));
        jButtonVerEstudiante.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButtonVerEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVerEstudiante.setText("Ver Estudiantes");
        jButtonVerEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregar1ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButtonVerEstudiante);
        jButtonVerEstudiante.setBounds(240, 600, 180, 30);


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed

        jTextFieldMatricula.setText("");
        jTextFieldNombre.setText("");
        jTextFieldApellido.setText("");
        jTextFieldAnioIngreso.setText("");
        jTextFieldCorreoElectronico.setText("");
        jTextFieldEdad.setText("");
        jTextFieldDomicilio.setText("");
        jTextFieldGenero.setText("");
        jTextFieldTipoEstudiante.setText("");
        jTextFieldNumeroTelefono.setText("");
        jTextFieldPromedioIngreso.setText("");
        jTextFieldModalidad.setText("");
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonActualizarActionPerformed

    private void jButtonAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAgregar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameActualizarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameActualizarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameActualizarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameActualizarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameActualizarEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonVerEstudiante;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelMatricula;
    private javax.swing.JLabel jLabelAnioIngreso;
    private javax.swing.JLabel jLabelCorreo3;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JLabel jLabelDomicilio;
    private javax.swing.JLabel jLabelGenero;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTipoEstudiante;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelPromedioIngreso;
    private javax.swing.JLabel jLabelModalidad;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldAnioIngreso;
    private javax.swing.JTextField jTextFieldCorreoElectronico;
    private javax.swing.JTextField jTextFieldEdad;
    private javax.swing.JTextField jTextFieldDomicilio;
    private javax.swing.JTextField jTextFieldGenero;
    private javax.swing.JTextField jTextFieldMatricula;
    private javax.swing.JTextField jTextFieldTipoEstudiante;
    private javax.swing.JTextField jTextFieldNumeroTelefono;
    private javax.swing.JTextField jTextFieldPromedioIngreso;
    private javax.swing.JTextField jTextFieldModalidad;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
