/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage.gui.empleados;

/**
 *
 * @author andre
 */
public class JFrameIngresoEstudiante extends javax.swing.JFrame {

    /** Creates new form JFrameEmpleados */
    public JFrameIngresoEstudiante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents

    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        // jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        // jDesktopPane1.setLayout(new java.awt.BorderLayout());
        jLabelTitulo = new javax.swing.JLabel();

        jLabelMatricula = new javax.swing.JLabel();
        jTextFieldMatricula = new javax.swing.JTextField();

        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();

        jLabelApellido1 = new javax.swing.JLabel();
        jTextFieldApellido1 = new javax.swing.JTextField();

        jLabelApellido2 = new javax.swing.JLabel();
        jTextFieldApellido2 = new javax.swing.JTextField();

        jLabelEdad = new javax.swing.JLabel();
        jTextFieldEdad = new javax.swing.JTextField();

        jLabelGenero = new javax.swing.JLabel();
        jTextFieldGenero = new javax.swing.JTextField();

        jLabelCorreo = new javax.swing.JLabel();
        jTextFieldCorreoElectronico = new javax.swing.JTextField();
        // jLabelCorreo = new javax.swing.JLabel();

        jLabelTelefono = new javax.swing.JLabel();
        jTextFieldNumeroTelefono = new javax.swing.JTextField();

        jLabelFecha = new javax.swing.JLabel();
        jTextFieldFechaDeInicio = new javax.swing.JTextField();

        jLabelNumClases = new javax.swing.JLabel();
        jTextFieldNumClases = new javax.swing.JTextField();

        jLabelCantidadHs = new javax.swing.JLabel();
        jTextFieldHorasSemanales = new javax.swing.JTextField();

        jButtonLimpiar = new javax.swing.JButton();

        jButtonAgregar = new javax.swing.JButton();
        jButtonAgregar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("INGRESAR ESTUDIANTE");
        jDesktopPane1.add(jLabelTitulo);
        jLabelTitulo.setBounds(120, 20, 430, 42);

        // Matricula
        jLabelMatricula.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelMatricula.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMatricula.setText("Matricula:");
        jDesktopPane1.add(jLabelMatricula);
        jLabelMatricula.setBounds(50, 80, 110, 28);

        jTextFieldMatricula.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldMatricula);
        jTextFieldMatricula.setBounds(400, 80, 191, 34);

        // Nombre
        jLabelNombre.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setText("Nombre:");
        jDesktopPane1.add(jLabelNombre);
        jLabelNombre.setBounds(50, 130, 98, 28);

        jTextFieldNombre.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldNombre);
        jTextFieldNombre.setBounds(400, 130, 191, 34);

        // Apellido 1
        jLabelApellido1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelApellido1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelApellido1.setText("Apellido Paterno:");
        jDesktopPane1.add(jLabelApellido1);
        jLabelApellido1.setBounds(50, 180, 180, 28);

        jTextFieldApellido1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldApellido1);
        jTextFieldApellido1.setBounds(400, 180, 191, 34);

        // Apellido 2
        jLabelApellido2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelApellido2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelApellido2.setText("Apellido Materno:");
        jDesktopPane1.add(jLabelApellido2);
        jLabelApellido2.setBounds(50, 230, 180, 28);

        jTextFieldApellido2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldApellido2);
        jTextFieldApellido2.setBounds(400, 230, 191, 34);

        // Edad
        jLabelEdad.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelEdad.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEdad.setText("Edad:");
        jDesktopPane1.add(jLabelEdad);
        jLabelEdad.setBounds(50, 280, 55, 24);

        jTextFieldEdad.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldEdad);
        jTextFieldEdad.setBounds(400, 280, 191, 34);

        // Genero
        jLabelGenero.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelGenero.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGenero.setText("Genero:");
        jDesktopPane1.add(jLabelGenero);
        jLabelGenero.setBounds(50, 330, 97, 24);

        jTextFieldGenero.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldGenero);
        jTextFieldGenero.setBounds(400, 330, 191, 34);

        // Numero de clases
        jLabelNumClases.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelNumClases.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumClases.setText("Numero de clases:");
        jDesktopPane1.add(jLabelNumClases);
        jLabelNumClases.setBounds(50, 380, 190, 24);

        jTextFieldNumClases.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldNumClases);
        jTextFieldNumClases.setBounds(400, 380, 191, 30);

        // Correo Electronico
        jLabelCorreo.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelCorreo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCorreo.setText("Correo Electronico");
        jDesktopPane1.add(jLabelCorreo);
        jLabelCorreo.setBounds(50, 430, 200, 40);

        jTextFieldCorreoElectronico.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldCorreoElectronico);
        jTextFieldCorreoElectronico.setBounds(400, 430, 191, 34);

        // Numero de telefono
        jLabelTelefono.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelTelefono.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTelefono.setText("Numero de telefono:");
        jDesktopPane1.add(jLabelTelefono);
        jLabelTelefono.setBounds(50, 480, 220, 40);

        jTextFieldNumeroTelefono.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldNumeroTelefono);
        jTextFieldNumeroTelefono.setBounds(400, 480, 191, 34);

        // Fecha de ingreso
        jLabelFecha.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelFecha.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFecha.setText("Fecha de inicio:");
        jDesktopPane1.add(jLabelFecha);
        jLabelFecha.setBounds(50, 530, 190, 40);

        jTextFieldFechaDeInicio.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldFechaDeInicio);
        jTextFieldFechaDeInicio.setBounds(400, 530, 191, 34);

        // Cantidad de horas semanales
        jLabelCantidadHs.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelCantidadHs.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCantidadHs.setText("Cantidad hs");
        jDesktopPane1.add(jLabelCantidadHs);
        jLabelCantidadHs.setBounds(50, 580, 120, 40);

        jTextFieldHorasSemanales.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldHorasSemanales);
        jTextFieldHorasSemanales.setBounds(400, 580, 191, 34);

        // Botones
        jButtonLimpiar.setBackground(new java.awt.Color(0, 32, 108));
        jButtonLimpiar.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButtonLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLimpiar.setText("Limpiar ");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButtonLimpiar);
        jButtonLimpiar.setBounds(170, 730, 142, 50);

        jButtonAgregar.setBackground(new java.awt.Color(0, 32, 108));
        jButtonAgregar.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButtonAgregar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButtonAgregar);
        jButtonAgregar.setBounds(340, 730, 140, 50);

        jButtonAgregar1.setBackground(new java.awt.Color(1, 26, 86));
        jButtonAgregar1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButtonAgregar1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAgregar1.setText("LISTA DE EMPLEADOS");
        jButtonAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregar1ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButtonAgregar1);
        jButtonAgregar1.setBounds(70, 800, 520, 60);

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 870));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonLimpiarActionPerformed
        jTextFieldMatricula.setText("");
        jTextFieldNombre.setText("");
        jTextFieldApellido1.setText("");
        jTextFieldApellido2.setText("");
        jTextFieldHorasSemanales.setText("");
        jTextFieldCorreoElectronico.setText("");
        jTextFieldEdad.setText("");
        jTextFieldFechaDeInicio.setText("");
        jTextFieldGenero.setText("");
        jTextFieldNumeroTelefono.setText("");
        jTextFieldNumClases.setText("");
    }// GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonAgregarActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButtonAgregar1ActionPerformed
        new JFrameVerEstudiante().setVisible(true);
    }// GEN-LAST:event_jButtonAgregar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameIngresoEstudiante.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameIngresoEstudiante.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameIngresoEstudiante.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameIngresoEstudiante.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameIngresoEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // BOTONES
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonAgregar1;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JDesktopPane jDesktopPane1;

    // LABELS
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelMatricula;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelApellido1;
    private javax.swing.JLabel jLabelApellido2;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JLabel jLabelGenero;
    private javax.swing.JLabel jLabelCorreo;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelCantidadHs;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelNumClases;

    // TEXT FIELDS
    private javax.swing.JTextField jTextFieldMatricula;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldApellido1;
    private javax.swing.JTextField jTextFieldApellido2;
    private javax.swing.JTextField jTextFieldEdad;
    private javax.swing.JTextField jTextFieldGenero;
    private javax.swing.JTextField jTextFieldCorreoElectronico;
    private javax.swing.JTextField jTextFieldNumeroTelefono;
    private javax.swing.JTextField jTextFieldHorasSemanales;
    private javax.swing.JTextField jTextFieldFechaDeInicio;
    private javax.swing.JTextField jTextFieldNumClases;
    // End of variables declaration//GEN-END:variables
}
