/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage.gui.empleados;

/**
 *
 * @author andre
 */
public class JFrameAnalytics extends javax.swing.JFrame {

    /** Creates new form JFrameAnalytics */
    public JFrameAnalytics() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelEdadMaxima = new javax.swing.JLabel();
        jTextFieldEdadMaxima = new javax.swing.JTextField();
        jLabelEdadMinima = new javax.swing.JLabel();
        jTextFieldEdadMinima = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelEdad = new javax.swing.JLabel();
        jLabelTotalServicios = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabelTotalTransporte = new javax.swing.JLabel();
        jLabelPrecioMaximoServicios = new javax.swing.JLabel();
        jTextFieldPrecioMaxServicios = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jLabelPrecioMaximoServicios1 = new javax.swing.JLabel();
        jTextFieldPrecioMinServicios = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        jLabelTotalServicios1 = new javax.swing.JLabel();
        jSeparator21 = new javax.swing.JSeparator();
        jSeparator22 = new javax.swing.JSeparator();
        jSeparator24 = new javax.swing.JSeparator();
        jTextFieldTotalTransporte = new javax.swing.JTextField();
        jLabelPrecioMaximoTransporte = new javax.swing.JLabel();
        jTextFieldPrecioMaxTransporte = new javax.swing.JTextField();
        jTextFieldPrecioMinTransporte = new javax.swing.JTextField();
        jLabelPrecioMinTransporte = new javax.swing.JLabel();
        jLabelEdadPromedio = new javax.swing.JLabel();
        jTextFieldEdadPromedio = new javax.swing.JTextField();
        jLabelEdadMasRepetido = new javax.swing.JLabel();
        jTextFieldEdadQueMasSeRepite = new javax.swing.JTextField();
        jLabelEdadPromedio2 = new javax.swing.JLabel();
        jLabelEdadMasRepetido2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Arial Black", 1, 28)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("ANALYTICS");
        jDesktopPane1.add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 6, -1, 50));

        jLabelEdadMaxima.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelEdadMaxima.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEdadMaxima.setText("Edad Máxima:");
        jDesktopPane1.add(jLabelEdadMaxima, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, 50));

        jTextFieldEdadMaxima.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextFieldEdadMaxima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEdadMaximaActionPerformed(evt);
            }
        });
        jTextFieldEdadMaxima.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEdadMaximaKeyTyped(evt);
            }
        });
        jDesktopPane1.add(jTextFieldEdadMaxima, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 150, 30));

        jLabelEdadMinima.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelEdadMinima.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEdadMinima.setText("Edad Mínima:");
        jDesktopPane1.add(jLabelEdadMinima, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 120, 40));

        jTextFieldEdadMinima.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextFieldEdadMinima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEdadMinimaActionPerformed(evt);
            }
        });
        jTextFieldEdadMinima.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEdadMinimaKeyTyped(evt);
            }
        });
        jDesktopPane1.add(jTextFieldEdadMinima, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 150, 30));
        jDesktopPane1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 570, 20));

        jLabelEdad.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jLabelEdad.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEdad.setText("EDAD");
        jDesktopPane1.add(jLabelEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, 50));

        jLabelTotalServicios.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jLabelTotalServicios.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTotalServicios.setText("NÚMERO DE DOCUMENTO");
        jDesktopPane1.add(jLabelTotalServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 310, 40));
        jDesktopPane1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 52, 270, 0));
        jDesktopPane1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 240, 30));
        jDesktopPane1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 260, -1));
        jDesktopPane1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 402, 220, 0));

        jLabelTotalTransporte.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelTotalTransporte.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTotalTransporte.setText("Precio Total: $");
        jDesktopPane1.add(jLabelTotalTransporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 670, -1, 50));

        jLabelPrecioMaximoServicios.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelPrecioMaximoServicios.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPrecioMaximoServicios.setText("Precio Máximo: $");
        jDesktopPane1.add(jLabelPrecioMaximoServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, -1, 50));

        jTextFieldPrecioMaxServicios.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextFieldPrecioMaxServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecioMaxServiciosActionPerformed(evt);
            }
        });
        jTextFieldPrecioMaxServicios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPrecioMaxServiciosKeyTyped(evt);
            }
        });
        jDesktopPane1.add(jTextFieldPrecioMaxServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 150, 30));
        jDesktopPane1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 92, 240, 0));
        jDesktopPane1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 260, 10));
        jDesktopPane1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 362, 270, 0));

        jLabelPrecioMaximoServicios1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelPrecioMaximoServicios1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPrecioMaximoServicios1.setText("Precio Mínimo: $");
        jDesktopPane1.add(jLabelPrecioMaximoServicios1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, -1, 50));

        jTextFieldPrecioMinServicios.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextFieldPrecioMinServicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecioMinServiciosActionPerformed(evt);
            }
        });
        jTextFieldPrecioMinServicios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPrecioMinServiciosKeyTyped(evt);
            }
        });
        jDesktopPane1.add(jTextFieldPrecioMinServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, 150, 30));
        jDesktopPane1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 230, -1));
        jDesktopPane1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 402, 180, 0));
        jDesktopPane1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 2, -1, 20));
        jDesktopPane1.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 440, -1));
        jDesktopPane1.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, -1, -1));
        jDesktopPane1.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 180, 0));
        jDesktopPane1.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 220, -1));
        jDesktopPane1.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 580, -1));
        jDesktopPane1.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 610, 240, -1));

        jLabelTotalServicios1.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        jLabelTotalServicios1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTotalServicios1.setText("TRANSPORTE");
        jDesktopPane1.add(jLabelTotalServicios1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 610, 160, 50));
        jDesktopPane1.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 652, 200, 0));
        jDesktopPane1.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 652, 200, 0));
        jDesktopPane1.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 660, 240, 20));

        jTextFieldTotalTransporte.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextFieldTotalTransporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalTransporteActionPerformed(evt);
            }
        });
        jTextFieldTotalTransporte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldTotalTransporteKeyTyped(evt);
            }
        });
        jDesktopPane1.add(jTextFieldTotalTransporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 680, 150, 30));

        jLabelPrecioMaximoTransporte.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelPrecioMaximoTransporte.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPrecioMaximoTransporte.setText("Precio Máximo: $");
        jDesktopPane1.add(jLabelPrecioMaximoTransporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 720, -1, 50));

        jTextFieldPrecioMaxTransporte.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextFieldPrecioMaxTransporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecioMaxTransporteActionPerformed(evt);
            }
        });
        jTextFieldPrecioMaxTransporte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPrecioMaxTransporteKeyTyped(evt);
            }
        });
        jDesktopPane1.add(jTextFieldPrecioMaxTransporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 730, 150, 30));

        jTextFieldPrecioMinTransporte.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextFieldPrecioMinTransporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPrecioMinTransporteActionPerformed(evt);
            }
        });
        jTextFieldPrecioMinTransporte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPrecioMinTransporteKeyTyped(evt);
            }
        });
        jDesktopPane1.add(jTextFieldPrecioMinTransporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 780, 150, 30));

        jLabelPrecioMinTransporte.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelPrecioMinTransporte.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPrecioMinTransporte.setText("Precio Mínimo: $");
        jDesktopPane1.add(jLabelPrecioMinTransporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 770, -1, 50));

        jLabelEdadPromedio.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelEdadPromedio.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEdadPromedio.setText("Edad Promedio:");
        jDesktopPane1.add(jLabelEdadPromedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 140, 30));

        jTextFieldEdadPromedio.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextFieldEdadPromedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEdadPromedioActionPerformed(evt);
            }
        });
        jTextFieldEdadPromedio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEdadPromedioKeyTyped(evt);
            }
        });
        jDesktopPane1.add(jTextFieldEdadPromedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 150, 30));

        jLabelEdadMasRepetido.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelEdadMasRepetido.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEdadMasRepetido.setText("Edad que más se repite:");
        jDesktopPane1.add(jLabelEdadMasRepetido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 210, 30));

        jTextFieldEdadQueMasSeRepite.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextFieldEdadQueMasSeRepite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEdadQueMasSeRepiteActionPerformed(evt);
            }
        });
        jTextFieldEdadQueMasSeRepite.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEdadQueMasSeRepiteKeyTyped(evt);
            }
        });
        jDesktopPane1.add(jTextFieldEdadQueMasSeRepite, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 150, 30));

        jLabelEdadPromedio2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelEdadPromedio2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEdadPromedio2.setText("(Media)");
        jDesktopPane1.add(jLabelEdadPromedio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 70, 30));

        jLabelEdadMasRepetido2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelEdadMasRepetido2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEdadMasRepetido2.setText("(Moda)");
        jDesktopPane1.add(jLabelEdadMasRepetido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 70, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldEdadMaximaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEdadMaximaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEdadMaximaActionPerformed

    private void jTextFieldEdadMaximaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEdadMaximaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEdadMaximaKeyTyped

    private void jTextFieldEdadMinimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEdadMinimaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEdadMinimaActionPerformed

    private void jTextFieldEdadMinimaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEdadMinimaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEdadMinimaKeyTyped

    private void jTextFieldPrecioMaxServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecioMaxServiciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioMaxServiciosActionPerformed

    private void jTextFieldPrecioMaxServiciosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrecioMaxServiciosKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioMaxServiciosKeyTyped

    private void jTextFieldPrecioMinServiciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecioMinServiciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioMinServiciosActionPerformed

    private void jTextFieldPrecioMinServiciosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrecioMinServiciosKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioMinServiciosKeyTyped

    private void jTextFieldTotalTransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalTransporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalTransporteActionPerformed

    private void jTextFieldTotalTransporteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTotalTransporteKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalTransporteKeyTyped

    private void jTextFieldPrecioMaxTransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecioMaxTransporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioMaxTransporteActionPerformed

    private void jTextFieldPrecioMaxTransporteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrecioMaxTransporteKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioMaxTransporteKeyTyped

    private void jTextFieldPrecioMinTransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPrecioMinTransporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioMinTransporteActionPerformed

    private void jTextFieldPrecioMinTransporteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPrecioMinTransporteKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPrecioMinTransporteKeyTyped

    private void jTextFieldEdadPromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEdadPromedioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEdadPromedioActionPerformed

    private void jTextFieldEdadPromedioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEdadPromedioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEdadPromedioKeyTyped

    private void jTextFieldEdadQueMasSeRepiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEdadQueMasSeRepiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEdadQueMasSeRepiteActionPerformed

    private void jTextFieldEdadQueMasSeRepiteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEdadQueMasSeRepiteKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEdadQueMasSeRepiteKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameAnalytics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameAnalytics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameAnalytics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAnalytics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameAnalytics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JLabel jLabelEdadMasRepetido;
    private javax.swing.JLabel jLabelEdadMasRepetido2;
    private javax.swing.JLabel jLabelEdadMaxima;
    private javax.swing.JLabel jLabelEdadMinima;
    private javax.swing.JLabel jLabelEdadPromedio;
    private javax.swing.JLabel jLabelEdadPromedio2;
    private javax.swing.JLabel jLabelPrecioMaximoServicios;
    private javax.swing.JLabel jLabelPrecioMaximoServicios1;
    private javax.swing.JLabel jLabelPrecioMaximoTransporte;
    private javax.swing.JLabel jLabelPrecioMinTransporte;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTotalServicios;
    private javax.swing.JLabel jLabelTotalServicios1;
    private javax.swing.JLabel jLabelTotalTransporte;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    public static javax.swing.JTextField jTextFieldEdadMaxima;
    public static javax.swing.JTextField jTextFieldEdadMinima;
    public static javax.swing.JTextField jTextFieldEdadPromedio;
    public static javax.swing.JTextField jTextFieldEdadQueMasSeRepite;
    public static javax.swing.JTextField jTextFieldPrecioMaxServicios;
    public static javax.swing.JTextField jTextFieldPrecioMaxTransporte;
    public static javax.swing.JTextField jTextFieldPrecioMinServicios;
    public static javax.swing.JTextField jTextFieldPrecioMinTransporte;
    public static javax.swing.JTextField jTextFieldTotalTransporte;
    // End of variables declaration//GEN-END:variables
}
