/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage.gui.empleados;

import mypackage.connector.LocalConnector;
import mypackage.entities.Student;
import mypackage.repositories.jdbc.StudentRepository;

import javax.swing.*;


/**
 *
 * @author andre
 */
public class JFrameActualizarStudent extends javax.swing.JFrame {


    /** Creates new form JFrameActualizarEmpleados */
    public JFrameActualizarStudent(Student student) {
        initComponents(student);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(Student student) {
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelAclaracion = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelApellido = new javax.swing.JLabel();
        jTextFieldApellido = new javax.swing.JTextField();
        jLabelEdad = new javax.swing.JLabel();
        jTextFieldEdad = new javax.swing.JTextField();
        jLabelGenero = new javax.swing.JLabel();
        jTextFieldGenero = new javax.swing.JTextField();
        jLabelTelefono = new javax.swing.JLabel();
        jTextFieldCorreo = new javax.swing.JTextField();
        jLabelCorreo = new javax.swing.JLabel();
        jLabelElectronico = new javax.swing.JLabel();
        jLabelNumeroMaterias = new javax.swing.JLabel();
        jLabelMaterias = new javax.swing.JLabel();
        jLabelCantidad = new javax.swing.JLabel();
        jTextFieldNumeroTelefono = new javax.swing.JTextField();
        jLabelMatricula = new javax.swing.JLabel();
        jTextFieldMaterias = new javax.swing.JTextField();
        jTextFieldMatricula = new javax.swing.JTextField();
        jLabelSemestre = new javax.swing.JLabel();
        jTextFieldSemestre = new javax.swing.JTextField();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonActualizar = new javax.swing.JButton();
        jButtonAgregar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelTitulo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("ACTUALIZACIÓN DE ALUMNOS");
        jDesktopPane1.add(jLabelTitulo);
        jLabelTitulo.setBounds(30, 20, 610, 42);

        jLabelAclaracion.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelAclaracion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelAclaracion.setText("LLene los campos que quiera actualizar");
        jDesktopPane1.add(jLabelAclaracion);
        jLabelAclaracion.setBounds(120, 60, 610, 42);

        jLabelNombre.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setText("Nombre:");
        jDesktopPane1.add(jLabelNombre);
        jLabelNombre.setBounds(170, 120, 98, 28);

        jTextFieldNombre.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldNombre);
        jTextFieldNombre.setBounds(260, 120, 191, 34);

        jLabelApellido.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelApellido.setForeground(new java.awt.Color(255, 255, 255));
        jLabelApellido.setText("Apellido:");
        jDesktopPane1.add(jLabelApellido);
        jLabelApellido.setBounds(170, 170, 104, 28);

        jTextFieldApellido.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldApellido);
        jTextFieldApellido.setBounds(260, 170, 191, 34);

        jLabelEdad.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelEdad.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEdad.setText("Edad:");
        jDesktopPane1.add(jLabelEdad);
        jLabelEdad.setBounds(200, 220, 55, 34);

        jTextFieldEdad.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldEdad);
        jTextFieldEdad.setBounds(260, 220, 191, 34);

        jLabelGenero.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelGenero.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGenero.setText("Genero:");
        jDesktopPane1.add(jLabelGenero);
        jLabelGenero.setBounds(180, 270, 77, 34);

        jTextFieldGenero.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldGenero);
        jTextFieldGenero.setBounds(260, 270, 191, 34);


        jLabelTelefono.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelTelefono.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTelefono.setText("Telefono:");
        jDesktopPane1.add(jLabelTelefono);
        jLabelTelefono.setBounds(155, 390, 120, 40);

        jTextFieldCorreo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldCorreo);
        jTextFieldCorreo.setBounds(260, 320, 191, 40);

        jLabelCorreo.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelCorreo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCorreo.setText("Correo");
        jDesktopPane1.add(jLabelCorreo);
        jLabelCorreo.setBounds(160, 310, 80, 30);

        jLabelElectronico.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelElectronico.setForeground(new java.awt.Color(255, 255, 255));
        jLabelElectronico.setText("electronico:");
        jDesktopPane1.add(jLabelElectronico);
        jLabelElectronico.setBounds(140, 330, 120, 40);

        jLabelNumeroMaterias.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelNumeroMaterias.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumeroMaterias.setText("Numero de");
        jDesktopPane1.add(jLabelNumeroMaterias);
        jLabelNumeroMaterias.setBounds(140, 370, 110, 30);


        jTextFieldNumeroTelefono.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldNumeroTelefono);
        jTextFieldNumeroTelefono.setBounds(260, 380, 191, 40);

        jLabelMaterias.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelMaterias.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMaterias.setText("Materias:");
        jDesktopPane1.add(jLabelMaterias);
        jLabelMaterias.setBounds(150, 450, 130, 40);

        jLabelCantidad.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelCantidad.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCantidad.setText("Cantidad de");
        jDesktopPane1.add(jLabelCantidad);
        jLabelCantidad.setBounds(140, 430, 130, 40);

        jLabelMatricula.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelMatricula.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMatricula.setText("Matricula:");
        jDesktopPane1.add(jLabelMatricula);
        jLabelMatricula.setBounds(150, 495, 130, 40);

        jTextFieldMaterias.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldMaterias);
        jTextFieldMaterias.setBounds(260, 440, 191, 40);

        jTextFieldMatricula.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldMatricula);
        jTextFieldMatricula.setBounds(260, 500, 191, 34);

        jLabelSemestre.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelSemestre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSemestre.setText("Semestre:");
        jDesktopPane1.add(jLabelSemestre);
        jLabelSemestre.setBounds(150, 550, 130, 40);


        jTextFieldSemestre.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldSemestre);
        jTextFieldSemestre.setBounds(260, 550, 191, 34);


        jButtonLimpiar.setBackground(new java.awt.Color(29, 122, 92));
        jButtonLimpiar.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButtonLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLimpiar.setText("Limpiar ");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButtonLimpiar);
        jButtonLimpiar.setBounds(160, 680, 142, 50);

        jButtonActualizar.setBackground(new java.awt.Color(29, 122, 92));
        jButtonActualizar.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButtonActualizar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonActualizar.setText("Actualizar");
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt,student);
            }
        });
        jDesktopPane1.add(jButtonActualizar);
        jButtonActualizar.setBounds(340, 680, 140, 50);

        jButtonAgregar1.setBackground(new java.awt.Color(29, 122, 92));
        jButtonAgregar1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButtonAgregar1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAgregar1.setText("Ver Students");
        jButtonAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregar1ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButtonAgregar1);
        jButtonAgregar1.setBounds(240, 760, 180, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed

        jTextFieldNombre.setText("");
        jTextFieldApellido.setText("");
        jTextFieldEdad.setText("");
        jTextFieldGenero.setText("");
        jTextFieldCorreo.setText("");
        jTextFieldNumeroTelefono.setText("");
        jTextFieldMaterias.setText("");
        jTextFieldMatricula.setText("");
        jTextFieldSemestre.setText("");
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt, Student student) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        StudentRepository repo= new StudentRepository(LocalConnector.getLocalConnection());
        String edad;
        String matricula;
        String semestre;
        String telefono;
        String materias;
        if(jTextFieldEdad.getText().isEmpty()){
            edad="0";
        }else {
            edad=jTextFieldEdad.getText();
        }
        if(jTextFieldMatricula.getText().isEmpty()){
            matricula="0";
        }else{
            matricula=jTextFieldMatricula.getText();
        }
        if(jTextFieldSemestre.getText().isEmpty()){
            semestre="0";
        }else{
            semestre=jTextFieldSemestre.getText();
        }
        if(jTextFieldNumeroTelefono.getText().isEmpty()){
            telefono="0";
        }else{
            telefono=jTextFieldNumeroTelefono.getText();
        }
        if(jTextFieldMaterias.getText().isEmpty()){
            materias="0";
        }else{
            materias=jTextFieldMaterias.getText();
        }
        try{
            Integer.parseInt(edad);
            Long.parseLong(telefono);
            Integer.parseInt(matricula);
            Integer.parseInt(semestre);
            Long.parseLong(matricula);
        }catch (NumberFormatException e){
            JOptionPane.showMessageDialog (this, "ALGUN CAMPO NUMERICO ES INVALIDO, ASEGURESE DE QUE SEAN NUMEROS VALIDOS");

            return;
        }
        repo.update(student,jTextFieldNombre.getText(),jTextFieldApellido.getText(),jTextFieldEdad.getText(),jTextFieldGenero.getText(),jTextFieldCorreo.getText(),jTextFieldNumeroTelefono.getText(),jTextFieldMaterias.getText(),jTextFieldMatricula.getText(),jTextFieldSemestre.getText());
        dispose();

    }//GEN-LAST:event_jButtonActualizarActionPerformed

    private void jButtonAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregar1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonAgregar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameActualizarStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameActualizarStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameActualizarStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameActualizarStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            Student student;
            public void run() {
                new JFrameActualizarStudent(student).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonAgregar1;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabelAclaracion;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelMaterias;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JLabel jLabelSemestre;
    private javax.swing.JLabel jLabelGenero;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelNumeroMaterias;
    private javax.swing.JLabel jLabelMatricula;
    private javax.swing.JLabel jLabelCorreo;
    private javax.swing.JLabel jLabelElectronico;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldMaterias;
    private javax.swing.JTextField jTextFieldEdad;
    private javax.swing.JTextField jTextFieldSemestre;
    private javax.swing.JTextField jTextFieldGenero;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNumeroTelefono;
    private javax.swing.JTextField jTextFieldMatricula;
    private javax.swing.JTextField jTextFieldCorreo;
    // End of variables declaration//GEN-END:variables
}
