/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage.gui.empleados;

import mypackage.connector.LocalConnector;
import mypackage.entities.Alumno;
import mypackage.repositories.interfaces.I_AlumnoRepository;
import mypackage.repositories.jdbc.AlumnoRepository;
import javax.swing.JOptionPane;


/**
 *
 * @author andre
 */
public class JFrameIngresoAlumno extends javax.swing.JFrame {


    private I_AlumnoRepository alumnoRepository;

    /** Creates new form JFrameEmpleados */
    public JFrameIngresoAlumno() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelApellido = new javax.swing.JLabel();
        jTextFieldApellido = new javax.swing.JTextField();
        jLabelEdad = new javax.swing.JLabel();
        jTextFieldEdad = new javax.swing.JTextField();
        jLabelGenero = new javax.swing.JLabel();
        jTextFieldGenero = new javax.swing.JTextField();
        jTextFieldSueldo = new javax.swing.JTextField();
        jLabelNumDoc2 = new javax.swing.JLabel();
        jLabelCorreo1 = new javax.swing.JLabel();
        jTextFieldTipoDoc = new javax.swing.JTextField();
        jLabelTipoDoc3 = new javax.swing.JLabel();
        jLabelTipoDoc4 = new javax.swing.JLabel();
        jLabelNumDoc3 = new javax.swing.JLabel();
        jLabelSueldo = new javax.swing.JLabel();
        jTextFieldMatricula = new javax.swing.JTextField();
        jLabelCorreo3 = new javax.swing.JLabel();
        jLabelNumero2 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelNumero3 = new javax.swing.JLabel();
        jLabelFecha2 = new javax.swing.JLabel();
        jTextFieldPromedio = new javax.swing.JTextField();
        jLabelFecha3 = new javax.swing.JLabel();
        jLabelCantidadHs1 = new javax.swing.JLabel();
        jTextFieldFechaIngreso = new javax.swing.JTextField();
        jLabelCantidadHs3 = new javax.swing.JLabel();
        jTextFieldCurso = new javax.swing.JTextField();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonAgregar = new javax.swing.JButton();
        jButtonAgregar1 = new javax.swing.JButton();
        alumnoRepository = new AlumnoRepository(LocalConnector.getLocalConnection());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("INGRESAR ALUMNO");
        jDesktopPane1.add(jLabelTitulo);
        jLabelTitulo.setBounds(120, 20, 430, 42);

        jLabelNombre.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setText("Nombre:");
        jDesktopPane1.add(jLabelNombre);
        jLabelNombre.setBounds(180, 80, 98, 28);

        jTextFieldNombre.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldNombre);
        jTextFieldNombre.setBounds(270, 80, 191, 34);

        jLabelApellido.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelApellido.setForeground(new java.awt.Color(255, 255, 255));
        jLabelApellido.setText("Apellido:");
        jDesktopPane1.add(jLabelApellido);
        jLabelApellido.setBounds(180, 130, 104, 28);

        jTextFieldApellido.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldApellido);
        jTextFieldApellido.setBounds(270, 130, 191, 34);

        jLabelEdad.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelEdad.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEdad.setText("Edad:");
        jDesktopPane1.add(jLabelEdad);
        jLabelEdad.setBounds(210, 190, 55, 24);

        jTextFieldEdad.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldEdad);
        jTextFieldEdad.setBounds(270, 180, 191, 34);

        jLabelGenero.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelGenero.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGenero.setText("Genero:");
        jDesktopPane1.add(jLabelGenero);
        jLabelGenero.setBounds(190, 240, 77, 24);

        jTextFieldGenero.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldGenero);
        jTextFieldGenero.setBounds(270, 240, 191, 34);

//        jTextFieldSueldo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
//        jDesktopPane1.add(jTextFieldSueldo);
//        jTextFieldSueldo.setBounds(270, 660, 191, 34);

        jLabelNumDoc2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelNumDoc2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumDoc2.setText("Email:");
        jDesktopPane1.add(jLabelNumDoc2);
        jLabelNumDoc2.setBounds(160, 360, 120, 40);

        jLabelCorreo1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelCorreo1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCorreo1.setText("Matrícula:");
        jDesktopPane1.add(jLabelCorreo1);
        jLabelCorreo1.setBounds(150, 420, 120, 40);

        jTextFieldTipoDoc.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldTipoDoc);
        jTextFieldTipoDoc.setBounds(270, 300, 191, 30);

//        jLabelTipoDoc3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
//        jLabelTipoDoc3.setForeground(new java.awt.Color(255, 255, 255));
//        jLabelTipoDoc3.setText("Tipo de");
//        jDesktopPane1.add(jLabelTipoDoc3);
//        jLabelTipoDoc3.setBounds(180, 270, 80, 30);

        jLabelTipoDoc4.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelTipoDoc4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTipoDoc4.setText("Curso:");
        jDesktopPane1.add(jLabelTipoDoc4);
        jLabelTipoDoc4.setBounds(150, 290, 120, 40);

//        jLabelNumDoc3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
//        jLabelNumDoc3.setForeground(new java.awt.Color(255, 255, 255));
//        jLabelNumDoc3.setText("Numero de");
//        jDesktopPane1.add(jLabelNumDoc3);
//        jLabelNumDoc3.setBounds(160, 340, 110, 30);

//        jLabelSueldo.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
//        jLabelSueldo.setForeground(new java.awt.Color(255, 255, 255));
//        jLabelSueldo.setText("Sueldo:");
//        jDesktopPane1.add(jLabelSueldo);
//        jLabelSueldo.setBounds(200, 660, 80, 40);

        jTextFieldMatricula.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldMatricula);
        jTextFieldMatricula.setBounds(270, 360, 191, 34);

//        jLabelCorreo3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
//        jLabelCorreo3.setForeground(new java.awt.Color(255, 255, 255));
//        jLabelCorreo3.setText("Correo");
//        jDesktopPane1.add(jLabelCorreo3);
//        jLabelCorreo3.setBounds(170, 400, 70, 40);

        jLabelNumero2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelNumero2.setForeground(new java.awt.Color(249, 247, 247));
        jLabelNumero2.setText("Promedio:");
        jDesktopPane1.add(jLabelNumero2);
        jLabelNumero2.setBounds(150, 480, 130, 40);

        jTextFieldEmail.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldEmail);
        jTextFieldEmail.setBounds(270, 420, 191, 34);

//        jLabelNumero3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
//        jLabelNumero3.setForeground(new java.awt.Color(255, 255, 255));
//        jLabelNumero3.setText("Numero ");
//        jDesktopPane1.add(jLabelNumero3);
//        //  jLabelNumero3.setBounds(170, 460, 110, 40);

        jLabelFecha2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelFecha2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFecha2.setText("de ingreso:");
        jDesktopPane1.add(jLabelFecha2);
        jLabelFecha2.setBounds(170, 540, 100, 40);

        jTextFieldPromedio.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldPromedio);
        jTextFieldPromedio.setBounds(270, 480, 191, 34);

        jLabelFecha3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelFecha3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFecha3.setText("Fecha ");
        jDesktopPane1.add(jLabelFecha3);
        jLabelFecha3.setBounds(180, 520, 90, 40);

//        jLabelCantidadHs1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
//        jLabelCantidadHs1.setForeground(new java.awt.Color(255, 255, 255));
//        jLabelCantidadHs1.setText("Cantidad hs");
//        jDesktopPane1.add(jLabelCantidadHs1);
//        jLabelCantidadHs1.setBounds(150, 580, 120, 40);

        jTextFieldFechaIngreso.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldFechaIngreso);
        jTextFieldFechaIngreso.setBounds(270, 540, 191, 34);

        jLabelCantidadHs3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabelCantidadHs3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCantidadHs3.setText("Id:");
        jDesktopPane1.add(jLabelCantidadHs3);
        jLabelCantidadHs3.setBounds(160, 600, 110, 40);

        jTextFieldCurso.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jDesktopPane1.add(jTextFieldCurso);
        jTextFieldCurso.setBounds(270, 600, 191, 34);

        jButtonLimpiar.setBackground(new java.awt.Color(39, 35, 153));
        jButtonLimpiar.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButtonLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLimpiar.setText("Limpiar ");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButtonLimpiar);
        jButtonLimpiar.setBounds(170, 730, 142, 50);

        jButtonAgregar.setBackground(new java.awt.Color(35, 55, 153));
        jButtonAgregar.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButtonAgregar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButtonAgregar);
        jButtonAgregar.setBounds(340, 730, 140, 50);

        jButtonAgregar1.setBackground(new java.awt.Color(35, 55, 153));
        jButtonAgregar1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButtonAgregar1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAgregar1.setText("LISTA DE ALUMNOS");
        jButtonAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregar1ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButtonAgregar1);
        jButtonAgregar1.setBounds(110, 650, 420, 50);

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 870));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed

        jTextFieldNombre.setText("");
        jTextFieldApellido.setText("");
        jTextFieldCurso.setText("");
        jTextFieldEmail.setText("");
        jTextFieldEdad.setText("");
        jTextFieldFechaIngreso.setText("");
        jTextFieldGenero.setText("");
        jTextFieldMatricula.setText("");
        jTextFieldPromedio.setText("");
//        jTextFieldSueldo.setText("");
//        jTextFieldTipoDoc.setText("");
    }//GEN-LAST:event_jButtonLimpiarActionPerformed





    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        // TODO add your handling code here:

        try {
            String nombre = jTextFieldNombre.getText();
            String apellido = jTextFieldApellido.getText();
            int edad = Integer.parseInt(jTextFieldEdad.getText());
            String genero = jTextFieldGenero.getText();
            String curso = jTextFieldCurso.getText();
            String matricula = jTextFieldMatricula.getText();
            double promedio = Double.parseDouble(jTextFieldPromedio.getText());
            String email = jTextFieldEmail.getText();
            String fecha_ingreso = jTextFieldFechaIngreso.getText();

            if (nombre.isEmpty() || apellido.isEmpty() || jTextFieldEdad.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor complete todos los campos obligatorios.");
                return;
            }


            Alumno nuevoAlumno = new Alumno(
                    0,
                    nombre,
                    apellido,
                    edad,
                    genero,
                    curso,
                    matricula,
                    promedio,
                    fecha_ingreso,
                    email
            );

            alumnoRepository.save(nuevoAlumno);

            JOptionPane.showMessageDialog(this, "✅ Alumno agregado correctamente.");

            jTextFieldNombre.setText("");
            jTextFieldApellido.setText("");
            jTextFieldEdad.setText("");
            jTextFieldGenero.setText("");
            jTextFieldCurso.setText("");
            jTextFieldMatricula.setText("");
            jTextFieldPromedio.setText("");
            jTextFieldEmail.setText("");
            jTextFieldFechaIngreso.setText("");

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "❌ Ingrese valores numéricos donde sea necesario.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "❌ Error al agregar el alumno.");
            ex.printStackTrace();
        }



    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregar1ActionPerformed
       new JFrameVerAlumno().setVisible(true);
    }//GEN-LAST:event_jButtonAgregar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameIngresoAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameIngresoAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameIngresoAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameIngresoAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameIngresoAlumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonAgregar1;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelCantidadHs1;
    private javax.swing.JLabel jLabelCantidadHs3;
    private javax.swing.JLabel jLabelCorreo1;
    private javax.swing.JLabel jLabelCorreo3;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JLabel jLabelFecha2;
    private javax.swing.JLabel jLabelFecha3;
    private javax.swing.JLabel jLabelGenero;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNumDoc2;
    private javax.swing.JLabel jLabelNumDoc3;
    private javax.swing.JLabel jLabelNumero2;
    private javax.swing.JLabel jLabelNumero3;
    private javax.swing.JLabel jLabelSueldo;
    private javax.swing.JLabel jLabelTipoDoc3;
    private javax.swing.JLabel jLabelTipoDoc4;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldCurso;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEdad;
    private javax.swing.JTextField jTextFieldFechaIngreso;
    private javax.swing.JTextField jTextFieldGenero;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldMatricula;
    private javax.swing.JTextField jTextFieldPromedio;
    private javax.swing.JTextField jTextFieldSueldo;
    private javax.swing.JTextField jTextFieldTipoDoc;
    // End of variables declaration//GEN-END:variables
}
