/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage.gui.utils;

import javax.swing.JOptionPane;
//import mypackage.gui.SoporteTecnico.JFrameIngresoSoporteTecnico;
import mypackage.gui.empleados.JFrameIngresoAlumno;

/**
 *
 * @author andre
 */
public class JFrameValidacionIngreso extends javax.swing.JFrame {

    /** Creates new form JFrameValidacion */
    public JFrameValidacionIngreso() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jLabelContraseña = new javax.swing.JLabel();
        jPasswordContraseña = new javax.swing.JPasswordField();
        jButtonValidar = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jLabelTitulo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("VALIDACIÓN DE INGRESO");
        jDesktopPane1.add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabelUsuario.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsuario.setText("Usuario:");
        jDesktopPane1.add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        jTextFieldUsuario.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jDesktopPane1.add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 191, 36));

        jLabelContraseña.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelContraseña.setForeground(new java.awt.Color(255, 255, 255));
        jLabelContraseña.setText("Contraseña:");
        jDesktopPane1.add(jLabelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        jPasswordContraseña.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jDesktopPane1.add(jPasswordContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 191, 36));

        jButtonValidar.setBackground(new java.awt.Color(0, 32, 108));
        jButtonValidar.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButtonValidar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonValidar.setText("Validar");
        jButtonValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonValidarActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButtonValidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 397, 162, 50));

        jButtonLimpiar.setBackground(new java.awt.Color(0, 32, 108));
        jButtonLimpiar.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jButtonLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLimpiar.setText("Limpiar ");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButtonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 397, 162, 50));

        jLabelTitulo1.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabelTitulo1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo1.setText("(Usuario-Contraseña por sector)");
        jDesktopPane1.add(jLabelTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonValidarActionPerformed
           

        
        if((jTextFieldUsuario.getText().equals("admin")) && (String.valueOf(jPasswordContraseña.getPassword()).equals("empleados"))){

             new JFrameIngresoAlumno().setVisible(true);

            dispose();

        }else if((jTextFieldUsuario.getText().equals("admin")) && (String.valueOf(jPasswordContraseña.getPassword()).equals("soporte"))){
            
             //new  JFrameIngresoSoporteTecnico().setVisible(true);

            dispose();
            
        }else{
                 JOptionPane.showMessageDialog(null, "EL USUARIO/CONTRASEÑA ES INVALIDO!");
                 
           
           
                }
        
        
        
        
        
        
        
        
        
//        boolean flagValidacionEntradaEmpleado = true;
//        boolean flagValidacionEntradaSoporteTecnico = true;
//        String flagSector="Ninguno";
//        
//        
//        while( (!(jTextFieldUsuario.getText().equals("admin"))
//                && !(jPasswordContraseña.getPassword().equals("1")) ) ){
//           
//            flagValidacionEntradaEmpleado = false;
//          
//           
//            JOptionPane.showMessageDialog(null, "EL USUARIO/CONTRASEÑA ES INVALIDO!");
//          
//            return;
//        }
//             while( (!(jTextFieldUsuario.getText().equals("admin"))
//                && !(jPasswordContraseña.getPassword().equals("2")) ) ){
//           
//            flagValidacionEntradaSoporteTecnico= false;
//          
//           
//            JOptionPane.showMessageDialog(null, "EL USUARIO/CONTRASEÑA ES INVALIDO!");
//          
//            return;
//        }
//
//        if ( jTextFieldUsuario.getText().equals("admin") ) {
//            
//            new  JFrameIngresoEmpleado().setVisible(true);
//
//            dispose();
//        }
//        else if(flagValidacionEntradaSoporteTecnico){
//           
//            new JFrameIngresoSoporteTecnico().setVisible(true);
//            
//            dispose();
//        }
//         
    }//GEN-LAST:event_jButtonValidarActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        
        jTextFieldUsuario.setText("");
        jPasswordContraseña.setText("");
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameValidacionIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameValidacionIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameValidacionIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameValidacionIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameValidacionIngreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonValidar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTitulo1;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPasswordField jPasswordContraseña;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
